studywords = [
{
"stimulus1":"<p style='font-size: 48px;'>EAGLE</p>","data1":{"phase":"study","type":"old","category":"birds","word":"EAGLE"},
"stimulus2":"<p style='font-size: 48px;'>ROBIN</p>","data2":{"phase":"study","type":"old","category":"birds","word":"ROBIN"},
"stimulus3":"<p style='font-size: 48px;'>BLUEJAY</p>","data3":{"phase":"study","type":"old","category":"birds","word":"BLUEJAY"},
"stimulus4":"<p style='font-size: 48px;'>CONCEPT</p>","data4":{"phase":"study","type":"distinct","category":"birds","word":"CONCEPT"},

"test1":"<p style='font-size: 48px;'>EAGLE</p>","data5":{"phase":"test","type":"old","category":"birds","test_type":"cat_test","word":"EAGLE"},
"test2":"<p style='font-size: 48px;'>ROBIN</p>","data6":{"phase":"test","type":"old","category":"birds","test_type":"cat_test","word":"ROBIN"},
"test3":"<p style='font-size: 48px;'>BLUEJAY</p>","data7":{"phase":"test","type":"old","category":"birds","test_type":"cat_test","word":"BLUEJAY"},
"test4":"<p style='font-size: 48px;'>CONCEPT</p>","data8":{"phase":"test","type":"old","category":"birds","test_type":"distinct_test","word":"CONCEPT"},
"test5":"<p style='font-size: 48px;'>SALES</p>","data9":{"phase":"test","type":"new","category":"birds","test_type":"unrelated_test","word":"SALES"},
},
{
"stimulus1":"<p style='font-size: 48px;'>BLUE</p>","data1":{"phase":"study","type":"old","category":"colors","word":"BLUE"},
"stimulus2":"<p style='font-size: 48px;'>RED</p>","data2":{"phase":"study","type":"old","category":"colors","word":"RED"},
"stimulus3":"<p style='font-size: 48px;'>GREEN</p>","data3":{"phase":"study","type":"old","category":"colors","word":"GREEN"},
"stimulus4":"<p style='font-size: 48px;'>TERRORISM</p>","data4":{"phase":"study","type":"distinct","category":"colors","word":"TERRORISM"},

"test1":"<p style='font-size: 48px;'>BLUE</p>","data5":{"phase":"test","type":"old","category":"colors","test_type":"cat_test","word":"BLUE"},
"test2":"<p style='font-size: 48px;'>RED</p>","data6":{"phase":"test","type":"old","category":"colors","test_type":"cat_test","word":"RED"},
"test3":"<p style='font-size: 48px;'>GREEN</p>","data7":{"phase":"test","type":"old","category":"colors","test_type":"cat_test","word":"GREEN"},
"test4":"<p style='font-size: 48px;'>TERRORISM</p>","data8":{"phase":"test","type":"old","category":"colors","test_type":"distinct_test","word":"TERRORISM"},
"test5":"<p style='font-size: 48px;'>COVER</p>","data9":{"phase":"test","type":"new","category":"colors","test_type":"unrelated_test","word":"COVER"},
},
{
"stimulus1":"<p style='font-size: 48px;'>GASOLINE</p>","data1":{"phase":"study","type":"old","category":"fuel","word":"GASOLINE"},
"stimulus2":"<p style='font-size: 48px;'>DIESEL</p>","data2":{"phase":"study","type":"old","category":"fuel","word":"DIESEL"},
"stimulus3":"<p style='font-size: 48px;'>OIL</p>","data3":{"phase":"study","type":"old","category":"fuel","word":"OIL"},
"stimulus4":"<p style='font-size: 48px;'>GATHER</p>","data4":{"phase":"study","type":"distinct","category":"fuel","word":"GATHER"},

"test1":"<p style='font-size: 48px;'>GASOLINE</p>","data5":{"phase":"test","type":"old","category":"fuel","test_type":"cat_test","word":"GASOLINE"},
"test2":"<p style='font-size: 48px;'>DIESEL</p>","data6":{"phase":"test","type":"old","category":"fuel","test_type":"cat_test","word":"DIESEL"},
"test3":"<p style='font-size: 48px;'>OIL</p>","data7":{"phase":"test","type":"old","category":"fuel","test_type":"cat_test","word":"OIL"},
"test4":"<p style='font-size: 48px;'>GATHER</p>","data8":{"phase":"test","type":"old", "category":"fuel","test_type":"distinct_test","word":"GATHER"},
"test5":"<p style='font-size: 48px;'>GRANDPARENT</p>","data9":{"phase":"test","type":"new","category":"fuel","test_type":"unrelated_test","word":"GRANDPARENT"},
},
{
"stimulus1":"<p style='font-size: 48px;'>HOUSE</p>","data1":{"phase":"study","type":"old","category":"dwelling","word":"HOUSE"},
"stimulus2":"<p style='font-size: 48px;'>APARTMENT</p>","data2":{"phase":"study","type":"old","category":"dwelling","word":"APARTMENT"},
"stimulus3":"<p style='font-size: 48px;'>MANSION</p>","data3":{"phase":"study","type":"old","category":"dwelling","word":"MANSION"},
"stimulus4":"<p style='font-size: 48px;'>HIRE</p>","data4":{"phase":"study","type":"distinct","category":"dwelling","word":"HIRE"},

"test1":"<p style='font-size: 48px;'>HOUSE</p>","data5":{"phase":"test","type":"old","category":"dwelling","test_type":"cat_test","word":"HOUSE"},
"test2":"<p style='font-size: 48px;'>APARTMENT</p>","data6":{"phase":"test","type":"old","category":"dwelling","test_type":"cat_test","word":"APARTMENT"},
"test3":"<p style='font-size: 48px;'>MANSION</p>","data7":{"phase":"test","type":"old","category":"dwelling","test_type":"cat_test","word":"MANSION"},
"test4":"<p style='font-size: 48px;'>HIRE</p>","data8":{"phase":"test","type":"old","category":"dwelling","test_type":"distinct_test","word":"HIRE"},
"test5":"<p style='font-size: 48px;'>MYTH</p>","data9":{"phase":"test","type":"new","category":"dwelling","test_type":"unrelated_test","word":"MYTH"},
},
{"stimulus1":"<p style='font-size: 48px;'>FOOTBALL</p>","data1":{"phase":"study","type":"old","category":"sports","word":"FOOTBALL"},
"stimulus2":"<p style='font-size: 48px;'>BASKETBALL</p>","data2":{"phase":"study","type":"old","category":"sports","word":"BASKETBALL"},
"stimulus3":"<p style='font-size: 48px;'>SOCCER</p>","data3":{"phase":"study","type":"old","category":"sports","word":"SOCCER"},
"stimulus4":"<p style='font-size: 48px;'>KNOW</p>","data4":{"phase":"study","type":"distinct","category":"sports","word":"KNOW"},

"test1":"<p style='font-size: 48px;'>FOOTBALL</p>","data5":{"phase":"test","type":"old","category":"sports","test_type":"cat_test","word":"FOOTBALL"},
"test2":"<p style='font-size: 48px;'>BASKETBALL</p>","data6":{"phase":"test","type":"old","category":"sports","test_type":"cat_test","word":"BASKETBALL"},
"test3":"<p style='font-size: 48px;'>SOCCER</p>","data7":{"phase":"test","type":"old","category":"sports","test_type":"cat_test","word":"SOCCER"},
"test4":"<p style='font-size: 48px;'>KNOW</p>","data8":{"phase":"test","type":"old","category":"sports","test_type":"distinct_test","word":"KNOW"},
"test5":"<p style='font-size: 48px;'>PUNISH</p>","data9":{"phase":"test","type":"new","category":"sports","test_type":"unrelated_test","word":"PUNISH"},
},
{"stimulus1":"<p style='font-size: 48px;'>MAGAZINE</p>","data1":{"phase":"study","type":"old","category":"reading","word":"MAGAZINE"},
"stimulus2":"<p style='font-size: 48px;'>BOOK</p>","data2":{"phase":"study","type":"old","category":"reading","word":"BOOK"},
"stimulus3":"<p style='font-size: 48px;'>NEWSPAPER</p>","data3":{"phase":"study","type":"old","category":"reading","word":"NEWSPAPER"},
"stimulus4":"<p style='font-size: 48px;'>TRAILER</p>","data4":{"phase":"study","type":"distinct","category":"reading","word":"TRAILER"},

"test1":"<p style='font-size: 48px;'>MAGAZINE</p>","data5":{"phase":"test","type":"old","category":"reading","test_type":"cat_test","word":"MAGAZINE"},
"test2":"<p style='font-size: 48px;'>BOOK</p>","data6":{"phase":"test","type":"old","category":"reading","test_type":"cat_test","word":"BOOK"},
"test3":"<p style='font-size: 48px;'>NEWSPAPER</p>","data7":{"phase":"test","type":"old","category":"reading","test_type":"cat_test","word":"NEWSPAPER"},
"test4":"<p style='font-size: 48px;'>TRAILER</p>","data8":{"phase":"test","type":"old","category":"reading","test_type":"distinct_test","word":"TRAILER"},
"test5":"<p style='font-size: 48px;'>ABSOLUTELY</p>","data9":{"phase":"test","type":"new","category":"reading","test_type":"unrelated_test","word":"ABSOLUTELY"},
},
{"stimulus1":"<p style='font-size: 48px;'>KNIFE</p>","data1":{"phase":"study","type":"old","category":"utensil","word":"KNIFE"},
"stimulus2":"<p style='font-size: 48px;'>FORK</p>","data2":{"phase":"study","type":"old","category":"utensil","word":"FORK"},
"stimulus3":"<p style='font-size: 48px;'>SPOON</p>","data3":{"phase":"study","type":"old","category":"utensil","word":"SPOON"},
"stimulus4":"<p style='font-size: 48px;'>BOLD</p>","data4":{"phase":"study","type":"distinct","category":"utensil","word":"BOLD"},

"test1":"<p style='font-size: 48px;'>KNIFE</p>","data5":{"phase":"test","type":"old","category":"utensil","test_type":"cat_test","word":"KNIFE"},
"test2":"<p style='font-size: 48px;'>FORK</p>","data6":{"phase":"test","type":"old","category":"utensil","test_type":"cat_test","word":"FORK"},
"test3":"<p style='font-size: 48px;'>SPOON</p>","data7":{"phase":"test","type":"old","category":"utensil","test_type":"cat_test","word":"SPOON"},
"test4":"<p style='font-size: 48px;'>BOLD</p>","data8":{"phase":"test","type":"old","category":"utensil","test_type":"distinct_test","word":"BOLD"},
"test5":"<p style='font-size: 48px;'>STRUCTURE</p>","data9":{"phase":"test","type":"new","category":"utensil","test_type":"unrelated_test","word":"STRUCTURE"},
},
{"stimulus1":"<p style='font-size: 48px;'>NOUN</p>","data1":{"phase":"study","type":"old","category":"speech","word":"NOUN"},
"stimulus2":"<p style='font-size: 48px;'>VERB</p>","data2":{"phase":"study","type":"old","category":"speech","word":"VERB"},
"stimulus3":"<p style='font-size: 48px;'>ADJECTIVE</p>","data3":{"phase":"study","type":"old","category":"speech","word":"ADJECTIVE"},
"stimulus4":"<p style='font-size: 48px;'>TENDENCY</p>","data4":{"phase":"study","type":"distinct","category":"speech","word":"TENDENCY"},

"test1":"<p style='font-size: 48px;'>NOUN</p>","data5":{"phase":"test","type":"old","category":"speech","test_type":"cat_test","word":"NOUN"},
"test2":"<p style='font-size: 48px;'>VERB</p>","data6":{"phase":"test","type":"old","category":"speech","test_type":"cat_test","word":"VERB"},
"test3":"<p style='font-size: 48px;'>ADJECTIVE</p>","data7":{"phase":"test","type":"old","category":"speech","test_type":"cat_test","word":"ADJECTIVE"},
"test4":"<p style='font-size: 48px;'>TENDENCY</p>","data8":{"phase":"test","type":"old","category":"speech","test_type":"distinct_test","word":"TENDENCY"},
"test5":"<p style='font-size: 48px;'>LEGISLATURE</p>","data9":{"phase":"test","type":"new","category":"speech","test_type":"unrelated_test","word":"LEGISLATURE"},
},
{"stimulus1":"<p style='font-size: 48px;'>DOLLAR</p>","data1":{"phase":"study","type":"old","category":"money","word":"DOLLAR"},
"stimulus2":"<p style='font-size: 48px;'>CENT</p>","data2":{"phase":"study","type":"old","category":"money","word":"CENT"},
"stimulus3":"<p style='font-size: 48px;'>DIME</p>","data3":{"phase":"study","type":"old","category":"money","word":"DIME"},
"stimulus4":"<p style='font-size: 48px;'>ROUTE</p>","data4":{"phase":"study","type":"distinct","category":"money","word":"ROUTE"},

"test1":"<p style='font-size: 48px;'>DOLLAR</p>","data5":{"phase":"test","type":"old","category":"money","test_type":"cat_test","word":"DOLLAR"},
"test2":"<p style='font-size: 48px;'>CENT</p>","data6":{"phase":"test","type":"old","category":"money","test_type":"cat_test","word":"CENT"},
"test3":"<p style='font-size: 48px;'>DIME</p>","data7":{"phase":"test","type":"old","category":"money","test_type":"cat_test","word":"DIME"},
"test4":"<p style='font-size: 48px;'>ROUTE</p>","data8":{"phase":"test","type":"old","category":"money","test_type":"distinct_test","word":"ROUTE"},
"test5":"<p style='font-size: 48px;'>BEGINNING</p>","data9":{"phase":"test","type":"new","category":"money","test_type":"unrelated_test","word":"BEGINNING"},
},
{"stimulus1":"<p style='font-size: 48px;'>HAMMER</p>","data1":{"phase":"study","type":"old","category":"tool","word":"HAMMER"},
"stimulus2":"<p style='font-size: 48px;'>NAIL</p>","data2":{"phase":"study","type":"old","category":"tool","word":"NAIL"},
"stimulus3":"<p style='font-size: 48px;'>SAW</p>","data3":{"phase":"study","type":"old","category":"tool","word":"SAW"},
"stimulus4":"<p style='font-size: 48px;'>INDEPENDENT</p>","data4":{"phase":"study","type":"distinct","category":"tool","word":"INDEPENDENT"},

"test1":"<p style='font-size: 48px;'>HAMMER</p>","data5":{"phase":"test","type":"old","category":"tool","test_type":"cat_test","word":"HAMMER"},
"test2":"<p style='font-size: 48px;'>NAIL</p>","data6":{"phase":"test","type":"old","category":"tool","test_type":"cat_test","word":"NAIL"},
"test3":"<p style='font-size: 48px;'>SAW</p>","data7":{"phase":"test","type":"old","category":"tool","test_type":"cat_test","word":"SAW"},
"test4":"<p style='font-size: 48px;'>INDEPENDENT</p>","data8":{"phase":"test","type":"old","category":"tool","test_type":"distinct_test","word":"INDEPENDENT"},
"test5":"<p style='font-size: 48px;'>CURIOUS</p>","data9":{"phase":"test","type":"new","category":"tool","test_type":"unrelated_test","word":"CURIOUS"},
},
{"stimulus1":"<p style='font-size: 48px;'>AMERICA</p>","data1":{"phase":"study","type":"old","category":"country","word":"AMERICA"},
"stimulus2":"<p style='font-size: 48px;'>CANADA</p>","data2":{"phase":"study","type":"old","category":"country","word":"CANADA"},
"stimulus3":"<p style='font-size: 48px;'>FRANCE</p>","data3":{"phase":"study","type":"old","category":"country","word":"FRANCE"},
"stimulus4":"<p style='font-size: 48px;'>SPECIAL</p>","data4":{"phase":"study","type":"distinct","category":"country","word":"SPECIAL"},

"test1":"<p style='font-size: 48px;'>AMERICA</p>","data5":{"phase":"test","type":"old","category":"country","test_type":"cat_test","word":"AMERICA"},
"test2":"<p style='font-size: 48px;'>CANADA</p>","data6":{"phase":"test","type":"old","category":"country","test_type":"cat_test","word":"CANADA"},
"test3":"<p style='font-size: 48px;'>FRANCE</p>","data7":{"phase":"test","type":"old","category":"country","test_type":"cat_test","word":"FRANCE"},
"test4":"<p style='font-size: 48px;'>SPECIAL</p>","data8":{"phase":"test","type":"old","category":"country","test_type":"distinct_test","word":"SPECIAL"},
"test5":"<p style='font-size: 48px;'>IMPLEMENT</p>","data9":{"phase":"test","type":"new","category":"country","test_type":"unrelated_test","word":"IMPLEMENT"},
},
{"stimulus1":"<p style='font-size: 48px;'>OXYGEN</p>","data1":{"phase":"study","type":"old","category":"element","word":"OXYGEN"},
"stimulus2":"<p style='font-size: 48px;'>HYDROGEN</p>","data2":{"phase":"study","type":"old","category":"element","word":"HYDROGEN"},
"stimulus3":"<p style='font-size: 48px;'>CARBON</p>","data3":{"phase":"study","type":"old","category":"element","word":"CARBON"},
"stimulus4":"<p style='font-size: 48px;'>CHIEF</p>","data4":{"phase":"study","type":"distinct","category":"element","word":"CHIEF"},

"test1":"<p style='font-size: 48px;'>OXYGEN</p>","data5":{"phase":"test","type":"old","category":"element","test_type":"cat_test","word":"OXYGEN"},
"test2":"<p style='font-size: 48px;'>HYDROGEN</p>","data6":{"phase":"test","type":"old","category":"element","test_type":"cat_test","word":"HYDROGEN"},
"test3":"<p style='font-size: 48px;'>CARBON</p>","data7":{"phase":"test","type":"old","category":"element","test_type":"cat_test","word":"CARBON"},
"test4":"<p style='font-size: 48px;'>CHIEF</p>","data8":{"phase":"test","type":"old","category":"element","test_type":"distinct_test","word":"CHIEF"},
"test5":"<p style='font-size: 48px;'>THIGH</p>","data9":{"phase":"test","type":"new","category":"element","test_type":"unrelated_test","word":"THIGH"},
},
{"stimulus1":"<p style='font-size: 48px;'>SHIRT</p>","data1":{"phase":"study","type":"old","category":"clothing","word":"SHIRT"},
"stimulus2":"<p style='font-size: 48px;'>PANTS</p>","data2":{"phase":"study","type":"old","category":"clothing","word":"PANTS"},
"stimulus3":"<p style='font-size: 48px;'>SOCKS</p>","data3":{"phase":"study","type":"old","category":"clothing","word":"SOCKS"},
"stimulus4":"<p style='font-size: 48px;'>ELIGIBLE</p>","data4":{"phase":"study","type":"distinct","category":"clothing","word":"ELIGIBLE"},

"test1":"<p style='font-size: 48px;'>SHIRT</p>","data5":{"phase":"test","type":"old","category":"clothing","test_type":"cat_test","word":"SHIRT"},
"test2":"<p style='font-size: 48px;'>PANTS</p>","data6":{"phase":"test","type":"old","category":"clothing","test_type":"cat_test","word":"PANTS"},
"test3":"<p style='font-size: 48px;'>SOCKS</p>","data7":{"phase":"test","type":"old","category":"clothing","test_type":"cat_test","word":"SOCKS"},
"test4":"<p style='font-size: 48px;'>ELIGIBLE</p>","data8":{"phase":"test","type":"old","category":"clothing","test_type":"distinct_test","word":"ELIGIBLE"},
"test5":"<p style='font-size: 48px;'>FURTHERMORE</p>","data9":{"phase":"test","type":"new","category":"clothing","test_type":"unrelated_test","word":"FURTHERMORE"},
},
{"stimulus1":"<p style='font-size: 48px;'>DRUMS</p>","data1":{"phase":"study","type":"old","category":"instrument","word":"DRUMS"},
"stimulus2":"<p style='font-size: 48px;'>GUITAR</p>","data2":{"phase":"study","type":"old","category":"instrument","word":"GUITAR"},
"stimulus3":"<p style='font-size: 48px;'>FLUTE</p>","data3":{"phase":"study","type":"old","category":"instrument","word":"FLUTE"},
"stimulus4":"<p style='font-size: 48px;'>SPOT</p>","data4":{"phase":"study","type":"distinct","category":"instrument","word":"SPOT"},

"test1":"<p style='font-size: 48px;'>DRUMS</p>","data5":{"phase":"test","type":"old","category":"instrument","test_type":"cat_test","word":"DRUMS"},
"test2":"<p style='font-size: 48px;'>GUITAR</p>","data6":{"phase":"test","type":"old","category":"instrument","test_type":"cat_test","word":"GUITAR"},
"test3":"<p style='font-size: 48px;'>FLUTE</p>","data7":{"phase":"test","type":"old","category":"instrument","test_type":"cat_test","word":"FLUTE"},
"test4":"<p style='font-size: 48px;'>SPOT</p>","data8":{"phase":"test","type":"old","category":"instrument","test_type":"distinct_test","word":"SPOT"},
"test5":"<p style='font-size: 48px;'>TYPICALLY</p>","data9":{"phase":"test","type":"new","category":"instrument","test_type":"unrelated_test","word":"TYPICALLY"},
},
{"stimulus1":"<p style='font-size: 48px;'>DIAMOND</p>","data1":{"phase":"study","type":"old","category":"stone","word":"DIAMOND"},
"stimulus2":"<p style='font-size: 48px;'>RUBY</p>","data2":{"phase":"study","type":"old","category":"stone","word":"RUBY"},
"stimulus3":"<p style='font-size: 48px;'>EMERALD</p>","data3":{"phase":"study","type":"old","category":"stone","word":"EMERALD"},
"stimulus4":"<p style='font-size: 48px;'>WRITING</p>","data4":{"phase":"study","type":"distinct","category":"stone","word":"WRITING"},

"test1":"<p style='font-size: 48px;'>DIAMOND</p>","data5":{"phase":"test","type":"old","category":"stone","test_type":"cat_test","word":"DIAMOND"},
"test2":"<p style='font-size: 48px;'>RUBY</p>","data6":{"phase":"test","type":"old","category":"stone","test_type":"cat_test","word":"RUBY"},
"test3":"<p style='font-size: 48px;'>EMERALD</p>","data7":{"phase":"test","type":"old","category":"stone","test_type":"cat_test","word":"EMERALD"},
"test4":"<p style='font-size: 48px;'>WRITING</p>","data8":{"phase":"test","type":"old","category":"stone","test_type":"distinct_test","word":">WRITING"},
"test5":"<p style='font-size: 48px;'>LIMITED</p>","data9":{"phase":"test","type":"new","category":"stone","test_type":"unrelated_test","word":"LIMITED"},
},
{"stimulus1":"<p style='font-size: 48px;'>OAK</p>","data1":{"phase":"study","type":"old","category":"tree","word":"OAK"},
"stimulus2":"<p style='font-size: 48px;'>PINE</p>","data2":{"phase":"study","type":"old","category":"tree","word":"PINE"},
"stimulus3":"<p style='font-size: 48px;'>MAPLE</p>","data3":{"phase":"study","type":"old","category":"tree","word":"MAPLE"},
"stimulus4":"<p style='font-size: 48px;'>RESPONSIBLE</p>","data4":{"phase":"study","type":"distinct","category":"tree","word":"RESPONSIBLE"},

"test1":"<p style='font-size: 48px;'>OAK</p>","data5":{"phase":"test","type":"old","category":"tree","test_type":"cat_test","word":"OAK"},
"test2":"<p style='font-size: 48px;'>PINE</p>","data6":{"phase":"test","type":"old","category":"tree","test_type":"cat_test","word":"PINE"},
"test3":"<p style='font-size: 48px;'>MAPLE</p>","data7":{"phase":"test","type":"old","category":"tree","test_type":"cat_test","word":"MAPLE"},
"test4":"<p style='font-size: 48px;'>RESPONSIBLE</p>","data8":{"phase":"test","type":"old","category":"tree","test_type":"distinct_test","word":"RESPONSIBLE"},
"test5":"<p style='font-size: 48px;'>FAITH</p>","data9":{"phase":"test","type":"new","category":"tree","test_type":"unrelated_test","word":"FAITH"},
},
{"stimulus1":"<p style='font-size: 48px;'>BALLET</p>","data1":{"phase":"study","type":"old","category":"dance","word":"BALLET"},
"stimulus2":"<p style='font-size: 48px;'>TANGO</p>","data2":{"phase":"study","type":"old","category":"dance","word":"TANGO"},
"stimulus3":"<p style='font-size: 48px;'>SALSA</p>","data3":{"phase":"study","type":"old","category":"dance","word":"SALSA"},
"stimulus4":"<p style='font-size: 48px;'>PEASANT</p>","data4":{"phase":"study","type":"distinct","category":"dance","word":"PEASANT"},

"test1":"<p style='font-size: 48px;'>BALLET</p>","data5":{"phase":"test","type":"old","category":"dance","test_type":"cat_test","word":"BALLET"},
"test2":"<p style='font-size: 48px;'>TANGO</p>","data6":{"phase":"test","type":"old","category":"dance","test_type":"cat_test","word":"TANGO"},
"test3":"<p style='font-size: 48px;'>SALSA</p>","data7":{"phase":"test","type":"old","category":"dance","test_type":"cat_test","word":"SALSA"},
"test4":"<p style='font-size: 48px;'>PEASANT</p>","data8":{"phase":"test","type":"old","category":"dance","test_type":"distinct_test","word":"PEASANT"},
"test5":"<p style='font-size: 48px;'>IMPORTANT</p>","data9":{"phase":"test","type":"new","category":"dance","test_type":"unrelated_test","word":"IMPORTANT"},
},
{"stimulus1":"<p style='font-size: 48px;'>CHAIR</p>","data1":{"phase":"study","type":"old","category":"furniture","word":"CHAIR"},
"stimulus2":"<p style='font-size: 48px;'>TABLE</p>","data2":{"phase":"study","type":"old","category":"furniture","word":"TABLE"},
"stimulus3":"<p style='font-size: 48px;'>COUCH</p>","data3":{"phase":"study","type":"old","category":"furniture","word":"COUCH"},
"stimulus4":"<p style='font-size: 48px;'>DISK</p>","data4":{"phase":"study","type":"distinct","category":"furniture","word":"DISK"},

"test1":"<p style='font-size: 48px;'>CHAIR</p>","data5":{"phase":"test","type":"old","category":"furniture","test_type":"cat_test","word":"CHAIR"},
"test2":"<p style='font-size: 48px;'>TABLE</p>","data6":{"phase":"test","type":"old","category":"furniture","test_type":"cat_test","word":"TABLE"},
"test3":"<p style='font-size: 48px;'>COUCH</p>","data7":{"phase":"test","type":"old","category":"furniture","test_type":"cat_test","word":"COUCH"},
"test4":"<p style='font-size: 48px;'>DISK</p>","data8":{"phase":"test","type":"old","category":"furniture","test_type":"distinct_test","word":"DISK"},
"test5":"<p style='font-size: 48px;'>SETTING</p>","data9":{"phase":"test","type":"new","category":"furniture","test_type":"unrelated_test","word":"SETTING"},
},
{"stimulus1":"<p style='font-size: 48px;'>DOCTOR</p>","data1":{"phase":"study","type":"old","category":"profession","word":"DOCTOR"},
"stimulus2":"<p style='font-size: 48px;'>TEACHER</p>","data2":{"phase":"study","type":"old","category":"profession","word":"TEACHER"},
"stimulus3":"<p style='font-size: 48px;'>LAWYER</p>","data3":{"phase":"study","type":"old","category":"profession","word":"LAWYER"},
"stimulus4":"<p style='font-size: 48px;'>INVISIBLE</p>","data4":{"phase":"study","type":"distinct","category":"profession","word":"INVISIBLE"},

"test1":"<p style='font-size: 48px;'>DOCTOR</p>","data5":{"phase":"test","type":"old","category":"profession","test_type":"cat_test","word":"DOCTOR"},
"test2":"<p style='font-size: 48px;'>TEACHER</p>","data6":{"phase":"test","type":"old","category":"profession","test_type":"cat_test","word":"TEACHER"},
"test3":"<p style='font-size: 48px;'>LAWYER</p>","data7":{"phase":"test","type":"old","category":"profession","test_type":"cat_test","word":"LAWYER"},
"test4":"<p style='font-size: 48px;'>INVISIBLE</p>","data8":{"phase":"test","type":"old","category":"profession","test_type":"distinct_test","word":"INVISIBLE"},
"test5":"<p style='font-size: 48px;'>IGNORE</p>","data9":{"phase":"test","type":"new","category":"profession","test_type":"unrelated_test","word":"IGNORE"},
},
{"stimulus1":"<p style='font-size: 48px;'>MOUNTAIN</p>","data1":{"phase":"study","type":"old","category":"earth","word":"MOUNTAIN"},
"stimulus2":"<p style='font-size: 48px;'>RIVER</p>","data2":{"phase":"study","type":"old","category":"earth","word":"RIVER"},
"stimulus3":"<p style='font-size: 48px;'>OCEAN</p>","data3":{"phase":"study","type":"old","category":"earth","word":"OCEAN"},
"stimulus4":"<p style='font-size: 48px;'>ENORMOUS</p>","data4":{"phase":"study","type":"distinct","category":"earth","word":"ENORMOUS"},

"test1":"<p style='font-size: 48px;'>MOUNTAIN</p>","data5":{"phase":"test","type":"old","category":"earth","test_type":"cat_test","word":"MOUNTAIN"},
"test2":"<p style='font-size: 48px;'>RIVER</p>","data6":{"phase":"test","type":"old","category":"earth","test_type":"cat_test","word":"RIVER"},
"test3":"<p style='font-size: 48px;'>OCEAN</p>","data7":{"phase":"test","type":"old","category":"earth","test_type":"cat_test","word":"OCEAN"},
"test4":"<p style='font-size: 48px;'>ENORMOUS</p>","data8":{"phase":"test","type":"old","category":"earth","test_type":"distinct_test","word":"ENORMOUS"},
"test5":"<p style='font-size: 48px;'>PILE</p>","data9":{"phase":"test","type":"new","category":"earth","test_type":"unrelated_test","word":"PILE"},
},
{"stimulus1":"<p style='font-size: 48px;'>APPLE</p>","data1":{"phase":"study","type":"old","category":"fruit","word":"APPLE"},
"stimulus2":"<p style='font-size: 48px;'>ORANGE</p>","data2":{"phase":"study","type":"old","category":"fruit","word":"ORANGE"},
"stimulus3":"<p style='font-size: 48px;'>BANANA</p>","data3":{"phase":"study","type":"old","category":"fruit","word":"BANANA"},
"stimulus4":"<p style='font-size: 48px;'>SUBSIDY</p>","data4":{"phase":"study","type":"distinct","category":"fruit","word":"SUBSIDY"},

"test1":"<p style='font-size: 48px;'>APPLE</p>","data5":{"phase":"test","type":"old","category":"fruit","test_type":"cat_test","word":"APPLE"},
"test2":"<p style='font-size: 48px;'>ORANGE</p>","data6":{"phase":"test","type":"old","category":"fruit","test_type":"cat_test","word":"ORANGE"},
"test3":"<p style='font-size: 48px;'>BANANA</p>","data7":{"phase":"test","type":"old","category":"fruit","test_type":"cat_test","word":"BANANA"},
"test4":"<p style='font-size: 48px;'>SUBSIDY</p>","data8":{"phase":"test","type":"old","category":"fruit","test_type":"distinct_test","word":"SUBSIDY"},
"test5":"<p style='font-size: 48px;'>GUIDELINE</p>","data9":{"phase":"test","type":"new","category":"fruit","test_type":"unrelated_test","word":"GUIDELINE"},
},
{"stimulus1":"<p style='font-size: 48px;'>AIDS</p>","data1":{"phase":"study","type":"old","category":"disease","word":"AIDS"},
"stimulus2":"<p style='font-size: 48px;'>CANCER</p>","data2":{"phase":"study","type":"old","category":"disease","word":"CANCER"},
"stimulus3":"<p style='font-size: 48px;'>FLU</p>","data3":{"phase":"study","type":"old","category":"disease","word":"FLU"},
"stimulus4":"<p style='font-size: 48px;'>FRIENDSHIP</p>","data4":{"phase":"study","type":"distinct","category":"disease","word":"FRIENDSHIP"},

"test1":"<p style='font-size: 48px;'>AIDS</p>","data5":{"phase":"test","type":"old","category":"disease","test_type":"cat_test","word":"AIDS"},
"test2":"<p style='font-size: 48px;'>CANCER</p>","data6":{"phase":"test","type":"old","category":"disease","test_type":"cat_test","word":"CANCER"},
"test3":"<p style='font-size: 48px;'>FLU</p>","data7":{"phase":"test","type":"old","category":"disease","test_type":"cat_test","word":"FLU"},
"test4":"<p style='font-size: 48px;'>FRIENDSHIP</p>","data8":{"phase":"test","type":"old","category":"disease","test_type":"distinct_test","word":"FRIENDSHIP"},
"test5":"<p style='font-size: 48px;'>FORTUNATELY</p>","data9":{"phase":"test","type":"new","category":"disease","test_type":"unrelated_test","word":"FORTUNATELY"},
},
{"stimulus1":"<p style='font-size: 48px;'>COTTON</p>","data1":{"phase":"study","type":"old","category":"fabric","word":"COTTON"},
"stimulus2":"<p style='font-size: 48px;'>SILK</p>","data2":{"phase":"study","type":"old","category":"fabric","word":"SILK"},
"stimulus3":"<p style='font-size: 48px;'>POLYESTER</p>","data3":{"phase":"study","type":"old","category":"fabric","word":"POLYESTER"},
"stimulus4":"<p style='font-size: 48px;'>FIFTH</p>","data4":{"phase":"study","type":"distinct","category":"fabric","word":"FIFTH"},

"test1":"<p style='font-size: 48px;'>COTTON</p>","data5":{"phase":"test","type":"old","category":"fabric","test_type":"cat_test","word":"COTTON"},
"test2":"<p style='font-size: 48px;'>SILK</p>","data6":{"phase":"test","type":"old","category":"fabric","test_type":"cat_test","word":"SILK"},
"test3":"<p style='font-size: 48px;'>POLYESTER</p>","data7":{"phase":"test","type":"old","category":"fabric","test_type":"cat_test","word":"POLYESTER"},
"test4":"<p style='font-size: 48px;'>FIFTH</p>","data8":{"phase":"test","type":"old","category":"fabric","test_type":"distinct_test","word":"FIFTH"},
"test5":"<p style='font-size: 48px;'>CONSEQUENCE</p>","data9":{"phase":"test","type":"new","category":"fabric","test_type":"unrelated_test","word":"CONSEQUENCE"},
},
{"stimulus1":"<p style='font-size: 48px;'>DOG</p>","data1":{"phase":"study","type":"old","category":"animal","word":"DOG"},
"stimulus2":"<p style='font-size: 48px;'>CAT</p>","data2":{"phase":"study","type":"old","category":"animal","word":"CAT"},
"stimulus3":"<p style='font-size: 48px;'>HORSE</p>","data3":{"phase":"study","type":"old","category":"animal","word":"HORSE"},
"stimulus4":"<p style='font-size: 48px;'>RARELY</p>","data4":{"phase":"study","type":"distinct","category":"animal","word":"RARELY"},

"test1":"<p style='font-size: 48px;'>DOG</p>","data5":{"phase":"test","type":"old","category":"animal","test_type":"cat_test","word":"DOG"},
"test2":"<p style='font-size: 48px;'>CAT</p>","data6":{"phase":"test","type":"old","category":"animal","test_type":"cat_test","word":"CAT"},
"test3":"<p style='font-size: 48px;'>HORSE</p>","data7":{"phase":"test","type":"old","category":"animal","test_type":"cat_test","word":"HORSE"},
"test4":"<p style='font-size: 48px;'>RARELY</p>","data8":{"phase":"test","type":"old","category":"animal","test_type":"distinct_test","word":"RARELY"},
"test5":"<p style='font-size: 48px;'>LIP</p>","data9":{"phase":"test","type":"new","category":"animal","test_type":"unrelated_test","word":"LIP"},
},
{"stimulus1":"<p style='font-size: 48px;'>ROSE</p>","data1":{"phase":"study","type":"old","category":"flower","word":"ROSE"},
"stimulus2":"<p style='font-size: 48px;'>DAISY</p>","data2":{"phase":"study","type":"old","category":"flower","word":"DAISY"},
"stimulus3":"<p style='font-size: 48px;'>TULIP</p>","data3":{"phase":"study","type":"old","category":"flower","word":"TULIP"},
"stimulus4":"<p style='font-size: 48px;'>SPECIFIC</p>","data4":{"phase":"study","type":"distinct","category":"flower","word":"SPECIFIC"},

"test1":"<p style='font-size: 48px;'>ROSE</p>","data5":{"phase":"test","type":"old","category":"flower","test_type":"cat_test","word":"ROSE"},
"test2":"<p style='font-size: 48px;'>DAISY</p>","data6":{"phase":"test","type":"old","category":"flower","test_type":"cat_test","word":"DAISY"},
"test3":"<p style='font-size: 48px;'>TULIP</p>","data7":{"phase":"test","type":"old","category":"flower","test_type":"cat_test","word":"TULIP"},
"test4":"<p style='font-size: 48px;'>SPECIFIC</p>","data8":{"phase":"test","type":"old","category":"flower","test_type":"distinct_test","word":"SPECIFIC"},
"test5":"<p style='font-size: 48px;'>MEAN</p>","data9":{"phase":"test","type":"new","category":"flower","test_type":"unrelated_test","word":"MEAN"},
},
{"stimulus1":"<p style='font-size: 48px;'>FORD</p>","data1":{"phase":"study","type":"old","category":"car","word":"FORD"},
"stimulus2":"<p style='font-size: 48px;'>HONDA</p>","data2":{"phase":"study","type":"old","category":"car","word":"HONDA"},
"stimulus3":"<p style='font-size: 48px;'>TOYOTA</p>","data3":{"phase":"study","type":"old","category":"car","word":"TOYOTA"},
"stimulus4":"<p style='font-size: 48px;'>STATISTICS</p>","data4":{"phase":"study","type":"distinct","category":"car","word":"STATISTICS"},

"test1":"<p style='font-size: 48px;'>FORD</p>","data5":{"phase":"test","type":"old","category":"car","test_type":"cat_test","word":"FORD"},
"test2":"<p style='font-size: 48px;'>HONDA</p>","data6":{"phase":"test","type":"old","category":"car","test_type":"cat_test","word":"HONDA"},
"test3":"<p style='font-size: 48px;'>TOYOTA</p>","data7":{"phase":"test","type":"old","category":"car","test_type":"cat_test","word":"TOYOTA"},
"test4":"<p style='font-size: 48px;'>STATISTICS</p>","data8":{"phase":"test","type":"old","category":"car","test_type":"distinct_test","word":"STATISTICS"},
"test5":"<p style='font-size: 48px;'>QUESTION</p>","data9":{"phase":"test","type":"new","category":"car","test_type":"unrelated_test","word":"QUESTION"},
},
{"stimulus1":"<p style='font-size: 48px;'>CALIFORNIA</p>","data1":{"phase":"study","type":"old","category":"state","word":"CALIFORNIA"},
"stimulus2":"<p style='font-size: 48px;'>COLORADO</p>","data2":{"phase":"study","type":"old","category":"state","word":"COLORADO"},
"stimulus3":"<p style='font-size: 48px;'>FLORIDA</p>","data3":{"phase":"study","type":"old","category":"state","word":"FLORIDA"},
"stimulus4":"<p style='font-size: 48px;'>STRICTLY</p>","data4":{"phase":"study","type":"distinct","category":"state","word":"STRICTLY"},

"test1":"<p style='font-size: 48px;'>CALIFORNIA</p>","data5":{"phase":"test","type":"old","category":"state","test_type":"cat_test","word":"CALIFORNIA"},
"test2":"<p style='font-size: 48px;'>COLORADO</p>","data6":{"phase":"test","type":"old","category":"state","test_type":"cat_test","word":"COLORADO"},
"test3":"<p style='font-size: 48px;'>FLORIDA</p>","data7":{"phase":"test","type":"old","category":"state","test_type":"cat_test","word":"FLORIDA"},
"test4":"<p style='font-size: 48px;'>STRICTLY</p>","data8":{"phase":"test","type":"old","category":"state","test_type":"distinct_test","word":"STRICTLY"},
"test5":"<p style='font-size: 48px;'>HALF</p>","data9":{"phase":"test","type":"new","category":"state","test_type":"unrelated_test","word":"HALF"},
},
{"stimulus1":"<p style='font-size: 48px;'>SALMON</p>","data1":{"phase":"study","type":"old","category":"fish","word":"SALMON"},
"stimulus2":"<p style='font-size: 48px;'>TROUT</p>","data2":{"phase":"study","type":"old","category":"fish","word":"TROUT"},
"stimulus3":"<p style='font-size: 48px;'>GOLDFISH</p>","data3":{"phase":"study","type":"old","category":"fish","word":"GOLDFISH"},
"stimulus4":"<p style='font-size: 48px;'>LEVEL</p>","data4":{"phase":"study","type":"distinct","category":"fish","word":"LEVEL"},

"test1":"<p style='font-size: 48px;'>SALMON</p>","data5":{"phase":"test","type":"old","category":"fish","test_type":"cat_test","word":"SALMON"},
"test2":"<p style='font-size: 48px;'>TROUT</p>","data6":{"phase":"test","type":"old","category":"fish","test_type":"cat_test","word":"TROUT"},
"test3":"<p style='font-size: 48px;'>GOLDFISH</p>","data7":{"phase":"test","type":"old","category":"fish","test_type":"cat_test","word":"GOLDFISH"},
"test4":"<p style='font-size: 48px;'>LEVEL</p>","data8":{"phase":"test","type":"old","category":"fish","test_type":"distinct_test","word":"LEVEL"},
"test5":"<p style='font-size: 48px;'>ENGLISH</p>","data9":{"phase":"test","type":"new","category":"fish","test_type":"unrelated_test","word":"ENGLISH"},
},
{"stimulus1":"<p style='font-size: 48px;'>SAILBOAT</p>","data1":{"phase":"study","type":"old","category":"boat","word":"SAILBOAT"},
"stimulus2":"<p style='font-size: 48px;'>CRUISE</p>","data2":{"phase":"study","type":"old","category":"boat","word":"CRUISE"},
"stimulus3":"<p style='font-size: 48px;'>YACHT</p>","data3":{"phase":"study","type":"old","category":"boat","word":"YACHT"},
"stimulus4":"<p style='font-size: 48px;'>ABLE</p>","data4":{"phase":"study","type":"distinct","category":"boat","word":"ABLE"},

"test1":"<p style='font-size: 48px;'>SAILBOAT</p>","data5":{"phase":"test","type":"old","category":"boat","test_type":"cat_test","word":"SAILBOAT"},
"test2":"<p style='font-size: 48px;'>CRUISE</p>","data6":{"phase":"test","type":"old","category":"boat","test_type":"cat_test","word":"CRUISE"},
"test3":"<p style='font-size: 48px;'>YACHT</p>","data7":{"phase":"test","type":"old","category":"boat","test_type":"cat_test","word":"YACHT"},
"test4":"<p style='font-size: 48px;'>ABLE</p>","data8":{"phase":"test","type":"old","category":"boat","test_type":"distinct_test","word":"ABLE"},
"test5":"<p style='font-size: 48px;'>ARGUMENT</p>","data9":{"phase":"test","type":"new","category":"boat","test_type":"unrelated_test","word":"ARGUMENT"},
},
{"stimulus1":"<p style='font-size: 48px;'>FLY</p>","data1":{"phase":"study","type":"old","category":"insect","word":"FLY"},
"stimulus2":"<p style='font-size: 48px;'>ANT</p>","data2":{"phase":"study","type":"old","category":"insect","word":"ANT"},
"stimulus3":"<p style='font-size: 48px;'>SPIDER</p>","data3":{"phase":"study","type":"old","category":"insect","word":"SPIDER"},
"stimulus4":"<p style='font-size: 48px;'>REGARDING</p>","data4":{"phase":"study","type":"distinct","category":"insect","word":"REGARDING"},

"test1":"<p style='font-size: 48px;'>FLY</p>","data5":{"phase":"test","type":"old","category":"insect","test_type":"cat_test","word":"FLY"},
"test2":"<p style='font-size: 48px;'>ANT</p>","data6":{"phase":"test","type":"old","category":"insect","test_type":"cat_test","word":"ANT"},
"test3":"<p style='font-size: 48px;'>SPIDER</p>","data7":{"phase":"test","type":"old","category":"insect","test_type":"cat_test","word":"SPIDER"},
"test4":"<p style='font-size: 48px;'>REGARDING</p>","data8":{"phase":"test","type":"old","category":"insect","test_type":"distinct_test","word":"REGARDING"},
"test5":"<p style='font-size: 48px;'>PHSYICALLY</p>","data9":{"phase":"test","type":"new","category":"insect","test_type":"unrelated_test","word":"PHSYICALLY"},
},
{"stimulus1":"<p style='font-size: 48px;'>TORNADO</p>","data1":{"phase":"study","type":"old","category":"weather","word":"TORNADO"},
"stimulus2":"<p style='font-size: 48px;'>HURRICANE</p>","data2":{"phase":"study","type":"old","category":"weather","word":"HURRICANE"},
"stimulus3":"<p style='font-size: 48px;'>RAIN</p>","data3":{"phase":"study","type":"old","category":"weather","word":"RAIN"},
"stimulus4":"<p style='font-size: 48px;'>OCCUR</p>","data4":{"phase":"study","type":"distinct","category":"weather","word":"OCCUR"},

"test1":"<p style='font-size: 48px;'>TORNADO</p>","data5":{"phase":"test","type":"old","category":"weather","test_type":"cat_test","word":"TORNADO"},
"test2":"<p style='font-size: 48px;'>HURRICANE</p>","data6":{"phase":"test","type":"old","category":"weather","test_type":"cat_test","word":"HURRICANE"},
"test3":"<p style='font-size: 48px;'>RAIN</p>","data7":{"phase":"test","type":"old","category":"weather","test_type":"cat_test","word":"RAIN"},
"test4":"<p style='font-size: 48px;'>OCCUR</p>","data8":{"phase":"test","type":"old","category":"weather","test_type":"distinct_test","word":"OCCUR"},
"test5":"<p style='font-size: 48px;'>HOSTILE</p>","data9":{"phase":"test","type":"new","category":"weather","test_type":"unrelated_test","word":"HOSTILE"},
},
{"stimulus1":"<p style='font-size: 48px;'>CARROT</p>","data1":{"phase":"study","type":"old","category":"vegetable","word":"CARROT"},
"stimulus2":"<p style='font-size: 48px;'>LETTUCE</p>","data2":{"phase":"study","type":"old","category":"vegetable","word":"LETTUCE"},
"stimulus3":"<p style='font-size: 48px;'>BROCCOLI</p>","data3":{"phase":"study","type":"old","category":"vegetable","word":"BROCCOLI"},
"stimulus4":"<p style='font-size: 48px;'>FOOL</p>","data4":{"phase":"study","type":"distinct","category":"vegetable","word":"FOOL"},

"test1":"<p style='font-size: 48px;'>CARROT</p>","data5":{"phase":"test","type":"old","category":"vegetable","test_type":"cat_test","word":"CARROT"},
"test2":"<p style='font-size: 48px;'>LETTUCE</p>","data6":{"phase":"test","type":"old","category":"vegetable","test_type":"cat_test","word":"LETTUCE"},
"test3":"<p style='font-size: 48px;'>BROCCOLI</p>","data7":{"phase":"test","type":"old","category":"vegetable","test_type":"cat_test","word":"BROCCOLI"},
"test4":"<p style='font-size: 48px;'>FOOL</p>","data8":{"phase":"test","type":"old","category":"vegetable","test_type":"distinct_test","word":"FOOL"},
"test5":"<p style='font-size: 48px;'>MARRIAGE</p>","data9":{"phase":"test","type":"new","category":"vegetable","test_type":"unrelated_test","word":"MARRIAGE"},
},
{"stimulus1":"<p style='font-size: 48px;'>BIOLOGY</p>","data1":{"phase":"study","type":"old","category":"science","word":"BIOLOGY"},
"stimulus2":"<p style='font-size: 48px;'>CHEMISTRY</p>","data2":{"phase":"study","type":"old","category":"science","word":"CHEMISTRY"},
"stimulus3":"<p style='font-size: 48px;'>PHYSICS</p>","data3":{"phase":"study","type":"old","category":"science","word":"PHYSICS"},
"stimulus4":"<p style='font-size: 48px;'>CODE</p>","data4":{"phase":"study","type":"distinct","category":"science","word":"CODE"},

"test1":"<p style='font-size: 48px;'>BIOLOGY</p>","data5":{"phase":"test","type":"old","category":"science","test_type":"cat_test","word":"BIOLOGY"},
"test2":"<p style='font-size: 48px;'>CHEMISTRY</p>","data6":{"phase":"test","type":"old","category":"science","test_type":"cat_test","word":"CHEMISTRY"},
"test3":"<p style='font-size: 48px;'>PHYSICS</p>","data7":{"phase":"test","type":"old","category":"science","test_type":"cat_test","word":"PHYSICS"},
"test4":"<p style='font-size: 48px;'>CODE</p>","data8":{"phase":"test","type":"old","category":"science","test_type":"distinct_test","word":"CODE"},
"test5":"<p style='font-size: 48px;'>PRESSURE</p>","data9":{"phase":"test","type":"new","category":"science","test_type":"unrelated_test","word":"PRESSURE"},
},
{"stimulus1":"<p style='font-size: 48px;'>WATER</p>","data1":{"phase":"study","type":"old","category":"beverage","word":"WATER"},
"stimulus2":"<p style='font-size: 48px;'>COKE</p>","data2":{"phase":"study","type":"old","category":"beverage","word":"COKE"},
"stimulus3":"<p style='font-size: 48px;'>MILK</p>","data3":{"phase":"study","type":"old","category":"beverage","word":"MILK"},
"stimulus4":"<p style='font-size: 48px;'>SHIFT</p>","data4":{"phase":"study","type":"distinct","category":"beverage","word":"SHIFT"},

"test1":"<p style='font-size: 48px;'>WATER</p>","data5":{"phase":"test","type":"old","category":"beverage","test_type":"cat_test","word":"WATER"},
"test2":"<p style='font-size: 48px;'>COKE</p>","data6":{"phase":"test","type":"old","category":"beverage","test_type":"cat_test","word":"COKE"},
"test3":"<p style='font-size: 48px;'>MILK</p>","data7":{"phase":"test","type":"old","category":"beverage","test_type":"cat_test","word":"MILK"},
"test4":"<p style='font-size: 48px;'>SHIFT</p>","data8":{"phase":"test","type":"old","category":"beverage","test_type":"distinct_test","word":"SHIFT"},
"test5":"<p style='font-size: 48px;'>CENTER</p>","data9":{"phase":"test","type":"new","category":"beverage","test_type":"unrelated_test","word":"CENTER"},
},
{"stimulus1":"<p style='font-size: 48px;'>RAP</p>","data1":{"phase":"study","type":"old","category":"music","word":"RAP"},
"stimulus2":"<p style='font-size: 48px;'>ROCK</p>","data2":{"phase":"study","type":"old","category":"music","word":"ROCK"},
"stimulus3":"<p style='font-size: 48px;'>CLASSICAL</p>","data3":{"phase":"study","type":"old","category":"music","word":"CLASSICAL"},
"stimulus4":"<p style='font-size: 48px;'>TOOTH</p>","data4":{"phase":"study","type":"distinct","category":"music","word":"TOOTH"},

"test1":"<p style='font-size: 48px;'>RAP</p>","data5":{"phase":"test","type":"old","category":"music","test_type":"cat_test","word":"RAP"},
"test2":"<p style='font-size: 48px;'>ROCK</p>","data6":{"phase":"test","type":"old","category":"music","test_type":"cat_test","word":"ROCK"},
"test3":"<p style='font-size: 48px;'>CLASSICAL</p>","data7":{"phase":"test","type":"old","category":"music","test_type":"cat_test","word":"CLASSICAL"},
"test4":"<p style='font-size: 48px;'>TOOTH</p>","data8":{"phase":"test","type":"old","category":"music","test_type":"distinct_test","word":"TOOTH"},
"test5":"<p style='font-size: 48px;'>SCARED</p>","data9":{"phase":"test","type":"new","category":"music","test_type":"unrelated_test","word":"SCARED"},
},
{"stimulus1":"<p style='font-size: 48px;'>WINDOW</p>","data1":{"phase":"study","type":"old","category":"buildingpart","word":"WINDOW"},
"stimulus2":"<p style='font-size: 48px;'>DOOR</p>","data2":{"phase":"study","type":"old","category":"buildingpart","word":"DOOR"},
"stimulus3":"<p style='font-size: 48px;'>FLOOR</p>","data3":{"phase":"study","type":"old","category":"buildingpart","word":"FLOOR"},
"stimulus4":"<p style='font-size: 48px;'>SHOCK</p>","data4":{"phase":"study","type":"distinct","category":"buildingpart","word":"SHOCK"},

"test1":"<p style='font-size: 48px;'>WINDOW</p>","data5":{"phase":"test","type":"old","category":"buildingpart","test_type":"cat_test","word":"WINDOW"},
"test2":"<p style='font-size: 48px;'>DOOR</p>","data6":{"phase":"test","type":"old","category":"buildingpart","test_type":"cat_test","word":"DOOR"},
"test3":"<p style='font-size: 48px;'>FLOOR</p>","data7":{"phase":"test","type":"old","category":"buildingpart","test_type":"cat_test","word":"FLOOR"},
"test4":"<p style='font-size: 48px;'>SHOCK</p>","data8":{"phase":"test","type":"old","category":"buildingpart","test_type":"distinct_test","word":"SHOCK"},
"test5":"<p style='font-size: 48px;'>ATTEMPT</p>","data9":{"phase":"test","type":"new","category":"buildingpart","test_type":"unrelated_test","word":"ATTEMPT"},
},
]
