studywords = [
{"stimulus1":"<p style='font-size: 48px;'>EAGLE</p>","data":{"type":"old","category":"birds","word":"EAGLE"},
"stimulus2":"<p style='font-size: 48px;'>ROBIN</p>","data":{"type":"old","category":"birds","word":"ROBIN"},
"stimulus3":"<p style='font-size: 48px;'>BLUEJAY</p>","data":{"type":"old","category":"birds","word":"BLUEJAY"},
"stimulus4":"<p style='font-size: 48px;'>CONCEPT</p>","data":{"type":"distinct","category":"birds","word":"CONCEPT"},
"test":"<p style='font-size: 48px;'>EAGLE</p>","data":{"type":"old","category":"birds","test_type":"cat_test","word":"EAGLE"}
},
{"stimulus1":"<p style='font-size: 48px;'>BLUE</p>","data":{"type":"old","category":"colors","word":"BLUE"},
"stimulus2":"<p style='font-size: 48px;'>RED</p>","data":{"type":"old","category":"colors","word":"RED"},
"stimulus3":"<p style='font-size: 48px;'>GREEN</p>","data":{"type":"old","category":"colors","word":"GREEN"},
"stimulus4":"<p style='font-size: 48px;'>TERRORISM</p>","data":{"type":"distinct","category":"colors","word":"TERRORISM"},
"test":"<p style='font-size: 48px;'>GREEN</p>","data":{"type":"old","category":"colors","test_type":"cat_test","word":"GREEN"}
},
{"stimulus1":"<p style='font-size: 48px;'>GASOLINE</p>","data":{"type":"old","category":"fuel","word":"GASOLINE"},
"stimulus2":"<p style='font-size: 48px;'>DIESEL</p>","data":{"type":"old","category":"fuel","word":"DIESEL"},
"stimulus3":"<p style='font-size: 48px;'>OIL</p>","data":{"type":"old","category":"fuel","word":"OIL"},
"stimulus4":"<p style='font-size: 48px;'>GATHER</p>","data":{"type":"distinct","category":"fuel","word":"GATHER"},
"test":"<p style='font-size: 48px;'>DIESEL</p>","data":{"type":"old","category":"fuel","test_type":"cat_test","word":"DIESEL"}
},
{"stimulus1":"<p style='font-size: 48px;'>HOUSE</p>","data":{"type":"old","category":"dwelling","word":"HOUSE"},
"stimulus2":"<p style='font-size: 48px;'>APARTMENT</p>","data":{"type":"old","category":"dwelling","word":"APARTMENT"},
"stimulus3":"<p style='font-size: 48px;'>MANSION</p>","data":{"type":"old","category":"dwelling","word":"MANSION"},
"stimulus4":"<p style='font-size: 48px;'>HIRE</p>","data":{"type":"distinct","category":"dwelling","word":"HIRE"},
"test":"<p style='font-size: 48px;'>MYTH</p>","data":{"type":"new","category":"dwelling","test_type":"unrelated_test","word":"MYTH"}
},
{"stimulus1":"<p style='font-size: 48px;'>FOOTBALL</p>","data":{"type":"old","category":"sports","word":"FOOTBALL"},
"stimulus2":"<p style='font-size: 48px;'>BASKETBALL</p>","data":{"type":"old","category":"sports","word":"BASKETBALL"},
"stimulus3":"<p style='font-size: 48px;'>SOCCER</p>","data":{"type":"old","category":"sports","word":"SOCCER"},
"stimulus4":"<p style='font-size: 48px;'>KNOW</p>","data":{"type":"distinct","category":"sports","word":"KNOW"},
"test":"<p style='font-size: 48px;'>PUNISH</p>","data":{"type":"new","category":"sports","test_type":"unrelated_test","word":"PUNISH"}
},
{"stimulus1":"<p style='font-size: 48px;'>MAGAZINE</p>","data":{"type":"old","category":"reading","word":"MAGAZINE"},
"stimulus2":"<p style='font-size: 48px;'>BOOK</p>","data":{"type":"old","category":"reading","word":"BOOK"},
"stimulus3":"<p style='font-size: 48px;'>NEWSPAPER</p>","data":{"type":"old","category":"reading","word":"NEWSPAPER"},
"stimulus4":"<p style='font-size: 48px;'>TRAILER</p>","data":{"type":"distinct","category":"reading","word":"TRAILER"},
"test":"<p style='font-size: 48px;'>TRAILER</p>","data":{"type":"old","category":"reading","test_type":"distinct_test","word":"TRAILER"}
},
{"stimulus1":"<p style='font-size: 48px;'>KNIFE</p>","data":{"type":"old","category":"utensil","word":"KNIFE"},
"stimulus2":"<p style='font-size: 48px;'>FORK</p>","data":{"type":"old","category":"utensil","word":"FORK"},
"stimulus3":"<p style='font-size: 48px;'>SPOON</p>","data":{"type":"old","category":"utensil","word":"SPOON"},
"stimulus4":"<p style='font-size: 48px;'>BOLD</p>","data":{"type":"distinct","category":"utensil","word":"BOLD"},
"test":"<p style='font-size: 48px;'>STRUCTURE</p>","data":{"type":"new","category":"utensil","test_type":"unrelated_test","word":"STRUCTURE"}
},
{"stimulus1":"<p style='font-size: 48px;'>NOUN</p>","data":{"type":"old","category":"speech","word":"NOUN"},
"stimulus2":"<p style='font-size: 48px;'>VERB</p>","data":{"type":"old","category":"speech","word":"VERB"},
"stimulus3":"<p style='font-size: 48px;'>ADJECTIVE</p>","data":{"type":"old","category":"speech","word":"ADJECTIVE"},
"stimulus4":"<p style='font-size: 48px;'>TENDENCY</p>","data":{"type":"distinct","category":"speech","word":"TENDENCY"},
"test":"<p style='font-size: 48px;'>ADJECTIVE</p>","data":{"type":"old","category":"speech","test_type":"cat_test","word":"ADJECTIVE"}
},
{"stimulus1":"<p style='font-size: 48px;'>DOLLAR</p>","data":{"type":"old","category":"money","word":"DOLLAR"},
"stimulus2":"<p style='font-size: 48px;'>CENT</p>","data":{"type":"old","category":"money","word":"CENT"},
"stimulus3":"<p style='font-size: 48px;'>DIME</p>","data":{"type":"old","category":"money","word":"DIME"},
"stimulus4":"<p style='font-size: 48px;'>ROUTE</p>","data":{"type":"distinct","category":"money","word":"ROUTE"},
"test":"<p style='font-size: 48px;'>BEGINNING</p>","data":{"type":"new","category":"money","test_type":"unrelated_test","word":"BEGINNING"}
},
{"stimulus1":"<p style='font-size: 48px;'>HAMMER</p>","data":{"type":"old","category":"tool","word":"HAMMER"},
"stimulus2":"<p style='font-size: 48px;'>NAIL</p>","data":{"type":"old","category":"tool","word":"NAIL"},
"stimulus3":"<p style='font-size: 48px;'>SAW</p>","data":{"type":"old","category":"tool","word":"SAW"},
"stimulus4":"<p style='font-size: 48px;'>INDEPENDENT</p>","data":{"type":"distinct","category":"tool","word":"INDEPENDENT"},
"test":"<p style='font-size: 48px;'>INDEPENDENT</p>","data":{"type":"old","category":"tool","test_type":"distinct_test","word":"INDEPENDENT"}
},
{"stimulus1":"<p style='font-size: 48px;'>AMERICA</p>","data":{"type":"old","category":"country","word":"AMERICA"},
"stimulus2":"<p style='font-size: 48px;'>CANADA</p>","data":{"type":"old","category":"country","word":"CANADA"},
"stimulus3":"<p style='font-size: 48px;'>FRANCE</p>","data":{"type":"old","category":"country","word":"FRANCE"},
"stimulus4":"<p style='font-size: 48px;'>SPECIAL</p>","data":{"type":"distinct","category":"country","word":"SPECIAL"},
"test":"<p style='font-size: 48px;'>SPECIAL</p>","data":{"type":"old","category":"country","test_type":"distinct_test","word":"SPECIAL"}
},
{"stimulus1":"<p style='font-size: 48px;'>OXYGEN</p>","data":{"type":"old","category":"element","word":"OXYGEN"},
"stimulus2":"<p style='font-size: 48px;'>HYDROGEN</p>","data":{"type":"old","category":"element","word":"HYDROGEN"},
"stimulus3":"<p style='font-size: 48px;'>CARBON</p>","data":{"type":"old","category":"element","word":"CARBON"},
"stimulus4":"<p style='font-size: 48px;'>CHIEF</p>","data":{"type":"distinct","category":"element","word":"CHIEF"},
"test":"<p style='font-size: 48px;'>THIGH</p>","data":{"type":"new","category":"element","test_type":"unrelated_test","word":"THIGH"}
},
{"stimulus1":"<p style='font-size: 48px;'>SHIRT</p>","data":{"type":"old","category":"clothing","word":"SHIRT"},
"stimulus2":"<p style='font-size: 48px;'>PANTS</p>","data":{"type":"old","category":"clothing","word":"PANTS"},
"stimulus3":"<p style='font-size: 48px;'>SOCKS</p>","data":{"type":"old","category":"clothing","word":"SOCKS"},
"stimulus4":"<p style='font-size: 48px;'>ELIGIBLE</p>","data":{"type":"distinct","category":"clothing","word":"ELIGIBLE"},
"test":"<p style='font-size: 48px;'>SHIRT</p>","data":{"type":"old","category":"clothing","test_type":"cat_test","word":"SHIRT"}
},
{"stimulus1":"<p style='font-size: 48px;'>DRUMS</p>","data":{"type":"old","category":"instrument","word":"DRUMS"},
"stimulus2":"<p style='font-size: 48px;'>GUITAR</p>","data":{"type":"old","category":"instrument","word":"GUITAR"},
"stimulus3":"<p style='font-size: 48px;'>FLUTE</p>","data":{"type":"old","category":"instrument","word":"FLUTE"},
"stimulus4":"<p style='font-size: 48px;'>SPOT</p>","data":{"type":"distinct","category":"instrument","word":"SPOT"},
"test":"<p style='font-size: 48px;'>TYPICALLY</p>","data":{"type":"new","category":"instrument","test_type":"unrelated_test","word":"TYPICALLY"}
},
{"stimulus1":"<p style='font-size: 48px;'>DIAMOND</p>","data":{"type":"old","category":"stone","word":"DIAMOND"},
"stimulus2":"<p style='font-size: 48px;'>RUBY</p>","data":{"type":"old","category":"stone","word":"RUBY"},
"stimulus3":"<p style='font-size: 48px;'>EMERALD</p>","data":{"type":"old","category":"stone","word":"EMERALD"},
"stimulus4":"<p style='font-size: 48px;'>WRITING</p>","data":{"type":"distinct","category":"stone","word":"WRITING"},
"test":"<p style='font-size: 48px;'>EMERALD</p>","data":{"type":"old","category":"stone","test_type":"cat_test","word":"EMERALD"}
},
{"stimulus1":"<p style='font-size: 48px;'>OAK</p>","data":{"type":"old","category":"tree","word":"OAK"},
"stimulus2":"<p style='font-size: 48px;'>PINE</p>","data":{"type":"old","category":"tree","word":"PINE"},
"stimulus3":"<p style='font-size: 48px;'>MAPLE</p>","data":{"type":"old","category":"tree","word":"MAPLE"},
"stimulus4":"<p style='font-size: 48px;'>RESPONSIBLE</p>","data":{"type":"distinct","category":"tree","word":"RESPONSIBLE"},
"test":"<p style='font-size: 48px;'>FAITH</p>","data":{"type":"new","category":"tree","test_type":"unrelated_test","word":"FAITH"}
},
{"stimulus1":"<p style='font-size: 48px;'>BALLET</p>","data":{"type":"old","category":"dance","word":"BALLET"},
"stimulus2":"<p style='font-size: 48px;'>TANGO</p>","data":{"type":"old","category":"dance","word":"TANGO"},
"stimulus3":"<p style='font-size: 48px;'>SALSA</p>","data":{"type":"old","category":"dance","word":"SALSA"},
"stimulus4":"<p style='font-size: 48px;'>PEASANT</p>","data":{"type":"distinct","category":"dance","word":"PEASANT"},
"test":"<p style='font-size: 48px;'>PEASANT</p>","data":{"type":"old","category":"dance","test_type":"distinct_test","word":"PEASANT"}
},
{"stimulus1":"<p style='font-size: 48px;'>CHAIR</p>","data":{"type":"old","category":"furniture","word":"CHAIR"},
"stimulus2":"<p style='font-size: 48px;'>TABLE</p>","data":{"type":"old","category":"furniture","word":"TABLE"},
"stimulus3":"<p style='font-size: 48px;'>COUCH</p>","data":{"type":"old","category":"furniture","word":"COUCH"},
"stimulus4":"<p style='font-size: 48px;'>DISK</p>","data":{"type":"distinct","category":"furniture","word":"DISK"},
"test":"<p style='font-size: 48px;'>SETTING</p>","data":{"type":"new","category":"furniture","test_type":"unrelated_test","word":"SETTING"}
},
{"stimulus1":"<p style='font-size: 48px;'>DOCTOR</p>","data":{"type":"old","category":"profession","word":"DOCTOR"},
"stimulus2":"<p style='font-size: 48px;'>TEACHER</p>","data":{"type":"old","category":"profession","word":"TEACHER"},
"stimulus3":"<p style='font-size: 48px;'>LAWYER</p>","data":{"type":"old","category":"profession","word":"LAWYER"},
"stimulus4":"<p style='font-size: 48px;'>INVISIBLE</p>","data":{"type":"distinct","category":"profession","word":"INVISIBLE"},
"test":"<p style='font-size: 48px;'>IGNORE</p>","data":{"type":"new","category":"profession","test_type":"unrelated_test","word":"IGNORE"}
},
{"stimulus1":"<p style='font-size: 48px;'>MOUNTAIN</p>","data":{"type":"old","category":"earth","word":"MOUNTAIN"},
"stimulus2":"<p style='font-size: 48px;'>RIVER</p>","data":{"type":"old","category":"earth","word":"RIVER"},
"stimulus3":"<p style='font-size: 48px;'>OCEAN</p>","data":{"type":"old","category":"earth","word":"OCEAN"},
"stimulus4":"<p style='font-size: 48px;'>ENORMOUS</p>","data":{"type":"distinct","category":"earth","word":"ENORMOUS"},
"test":"<p style='font-size: 48px;'>ENORMOUS</p>","data":{"type":"old","category":"earth","test_type":"distinct_test","word":"ENORMOUS"}
},
{"stimulus1":"<p style='font-size: 48px;'>APPLE</p>","data":{"type":"old","category":"fruit","word":"APPLE"},
"stimulus2":"<p style='font-size: 48px;'>ORANGE</p>","data":{"type":"old","category":"fruit","word":"ORANGE"},
"stimulus3":"<p style='font-size: 48px;'>BANANA</p>","data":{"type":"old","category":"fruit","word":"BANANA"},
"stimulus4":"<p style='font-size: 48px;'>SUBSIDY</p>","data":{"type":"distinct","category":"fruit","word":"SUBSIDY"},
"test":"<p style='font-size: 48px;'>SUBSIDY</p>","data":{"type":"old","category":"fruit","test_type":"distinct_test","word":"SUBSIDY"}
},
{"stimulus1":"<p style='font-size: 48px;'>AIDS</p>","data":{"type":"old","category":"disease","word":"AIDS"},
"stimulus2":"<p style='font-size: 48px;'>CANCER</p>","data":{"type":"old","category":"disease","word":"CANCER"},
"stimulus3":"<p style='font-size: 48px;'>FLU</p>","data":{"type":"old","category":"disease","word":"FLU"},
"stimulus4":"<p style='font-size: 48px;'>FRIENDSHIP</p>","data":{"type":"distinct","category":"disease","word":"FRIENDSHIP"},
"test":"<p style='font-size: 48px;'>CANCER</p>","data":{"type":"old","category":"disease","test_type":"cat_test","word":"CANCER"}
},
{"stimulus1":"<p style='font-size: 48px;'>COTTON</p>","data":{"type":"old","category":"fabric","word":"COTTON"},
"stimulus2":"<p style='font-size: 48px;'>SILK</p>","data":{"type":"old","category":"fabric","word":"SILK"},
"stimulus3":"<p style='font-size: 48px;'>POLYESTER</p>","data":{"type":"old","category":"fabric","word":"POLYESTER"},
"stimulus4":"<p style='font-size: 48px;'>FIFTH</p>","data":{"type":"distinct","category":"fabric","word":"FIFTH"},
"test":"<p style='font-size: 48px;'>CONSEQUENCE</p>","data":{"type":"new","category":"fabric","test_type":"unrelated_test","word":"CONSEQUENCE"}
},
{"stimulus1":"<p style='font-size: 48px;'>DOG</p>","data":{"type":"old","category":"animal","word":"DOG"},
"stimulus2":"<p style='font-size: 48px;'>CAT</p>","data":{"type":"old","category":"animal","word":"CAT"},
"stimulus3":"<p style='font-size: 48px;'>HORSE</p>","data":{"type":"old","category":"animal","word":"HORSE"},
"stimulus4":"<p style='font-size: 48px;'>RARELY</p>","data":{"type":"distinct","category":"animal","word":"RARELY"},
"test":"<p style='font-size: 48px;'>RARELY</p>","data":{"type":"old","category":"animal","test_type":"distinct_test","word":"RARELY"}
},
{"stimulus1":"<p style='font-size: 48px;'>ROSE</p>","data":{"type":"old","category":"flower","word":"ROSE"},
"stimulus2":"<p style='font-size: 48px;'>DAISY</p>","data":{"type":"old","category":"flower","word":"DAISY"},
"stimulus3":"<p style='font-size: 48px;'>TULIP</p>","data":{"type":"old","category":"flower","word":"TULIP"},
"stimulus4":"<p style='font-size: 48px;'>SPECIFIC</p>","data":{"type":"distinct","category":"flower","word":"SPECIFIC"},
"test":"<p style='font-size: 48px;'>ROSE</p>","data":{"type":"old","category":"flower","test_type":"cat_test","word":"ROSE"}
},
{"stimulus1":"<p style='font-size: 48px;'>FORD</p>","data":{"type":"old","category":"car","word":"FORD"},
"stimulus2":"<p style='font-size: 48px;'>HONDA</p>","data":{"type":"old","category":"car","word":"HONDA"},
"stimulus3":"<p style='font-size: 48px;'>TOYOTA</p>","data":{"type":"old","category":"car","word":"TOYOTA"},
"stimulus4":"<p style='font-size: 48px;'>STATISTICS</p>","data":{"type":"distinct","category":"car","word":"STATISTICS"},
"test":"<p style='font-size: 48px;'>QUESTION</p>","data":{"type":"new","category":"car","test_type":"unrelated_test","word":"QUESTION"}
},
{"stimulus1":"<p style='font-size: 48px;'>CALIFORNIA</p>","data":{"type":"old","category":"state","word":"CALIFORNIA"},
"stimulus2":"<p style='font-size: 48px;'>COLORADO</p>","data":{"type":"old","category":"state","word":"COLORADO"},
"stimulus3":"<p style='font-size: 48px;'>FLORIDA</p>","data":{"type":"old","category":"state","word":"FLORIDA"},
"stimulus4":"<p style='font-size: 48px;'>STRICTLY</p>","data":{"type":"distinct","category":"state","word":"STRICTLY"},
"test":"<p style='font-size: 48px;'>STRICTLY</p>","data":{"type":"old","category":"state","test_type":"distinct_test","word":"STRICTLY"}
},
{"stimulus1":"<p style='font-size: 48px;'>SALMON</p>","data":{"type":"old","category":"fish","word":"SALMON"},
"stimulus2":"<p style='font-size: 48px;'>TROUT</p>","data":{"type":"old","category":"fish","word":"TROUT"},
"stimulus3":"<p style='font-size: 48px;'>GOLDFISH</p>","data":{"type":"old","category":"fish","word":"GOLDFISH"},
"stimulus4":"<p style='font-size: 48px;'>LEVEL</p>","data":{"type":"distinct","category":"fish","word":"LEVEL"},
"test":"<p style='font-size: 48px;'>GOLDFISH</p>","data":{"type":"old","category":"fish","test_type":"cat_test","word":"GOLDFISH"}
},
{"stimulus1":"<p style='font-size: 48px;'>SAILBOAT</p>","data":{"type":"old","category":"boat","word":"SAILBOAT"},
"stimulus2":"<p style='font-size: 48px;'>CRUISE</p>","data":{"type":"old","category":"boat","word":"CRUISE"},
"stimulus3":"<p style='font-size: 48px;'>YACHT</p>","data":{"type":"old","category":"boat","word":"YACHT"},
"stimulus4":"<p style='font-size: 48px;'>ABLE</p>","data":{"type":"distinct","category":"boat","word":"ABLE"},
"test":"<p style='font-size: 48px;'>ABLE</p>","data":{"type":"old","category":"boat","test_type":"distinct_test","word":"ABLE"}
},
{"stimulus1":"<p style='font-size: 48px;'>FLY</p>","data":{"type":"old","category":"insect","word":"FLY"},
"stimulus2":"<p style='font-size: 48px;'>ANT</p>","data":{"type":"old","category":"insect","word":"ANT"},
"stimulus3":"<p style='font-size: 48px;'>SPIDER</p>","data":{"type":"old","category":"insect","word":"SPIDER"},
"stimulus4":"<p style='font-size: 48px;'>REGARDING</p>","data":{"type":"distinct","category":"insect","word":"REGARDING"},
"test":"<p style='font-size: 48px;'>PHSYICALLY</p>","data":{"type":"new","category":"insect","test_type":"unrelated_test","word":"PHSYICALLY"}
},
{"stimulus1":"<p style='font-size: 48px;'>TORNADO</p>","data":{"type":"old","category":"weather","word":"TORNADO"},
"stimulus2":"<p style='font-size: 48px;'>HURRICANE</p>","data":{"type":"old","category":"weather","word":"HURRICANE"},
"stimulus3":"<p style='font-size: 48px;'>RAIN</p>","data":{"type":"old","category":"weather","word":"RAIN"},
"stimulus4":"<p style='font-size: 48px;'>OCCUR</p>","data":{"type":"distinct","category":"weather","word":"OCCUR"},
"test":"<p style='font-size: 48px;'>HOSTILE</p>","data":{"type":"new","category":"weather","test_type":"unrelated_test","word":"HOSTILE"}
},
{"stimulus1":"<p style='font-size: 48px;'>CARROT</p>","data":{"type":"old","category":"vegetable","word":"CARROT"},
"stimulus2":"<p style='font-size: 48px;'>LETTUCE</p>","data":{"type":"old","category":"vegetable","word":"LETTUCE"},
"stimulus3":"<p style='font-size: 48px;'>BROCCOLI</p>","data":{"type":"old","category":"vegetable","word":"BROCCOLI"},
"stimulus4":"<p style='font-size: 48px;'>FOOL</p>","data":{"type":"distinct","category":"vegetable","word":"FOOL"},
"test":"<p style='font-size: 48px;'>MARRIAGE</p>","data":{"type":"new","category":"vegetable","test_type":"unrelated_test","word":"MARRIAGE"}
},
{"stimulus1":"<p style='font-size: 48px;'>BIOLOGY</p>","data":{"type":"old","category":"science","word":"BIOLOGY"},
"stimulus2":"<p style='font-size: 48px;'>CHEMISTRY</p>","data":{"type":"old","category":"science","word":"CHEMISTRY"},
"stimulus3":"<p style='font-size: 48px;'>PHYSICS</p>","data":{"type":"old","category":"science","word":"PHYSICS"},
"stimulus4":"<p style='font-size: 48px;'>CODE</p>","data":{"type":"distinct","category":"science","word":"CODE"},
"test":"<p style='font-size: 48px;'>PRESSURE</p>","data":{"type":"new","category":"science","test_type":"unrelated_test","word":"PRESSURE"}
},
{"stimulus1":"<p style='font-size: 48px;'>WATER</p>","data":{"type":"old","category":"beverage","word":"WATER"},
"stimulus2":"<p style='font-size: 48px;'>COKE</p>","data":{"type":"old","category":"beverage","word":"COKE"},
"stimulus3":"<p style='font-size: 48px;'>MILK</p>","data":{"type":"old","category":"beverage","word":"MILK"},
"stimulus4":"<p style='font-size: 48px;'>SHIFT</p>","data":{"type":"distinct","category":"beverage","word":"SHIFT"},
"test":"<p style='font-size: 48px;'>CENTER</p>","data":{"type":"new","category":"beverage","test_type":"unrelated_test","word":"CENTER"}
},
{"stimulus1":"<p style='font-size: 48px;'>RAP</p>","data":{"type":"old","category":"music","word":"RAP"},
"stimulus2":"<p style='font-size: 48px;'>ROCK</p>","data":{"type":"old","category":"music","word":"ROCK"},
"stimulus3":"<p style='font-size: 48px;'>CLASSICAL</p>","data":{"type":"old","category":"music","word":"CLASSICAL"},
"stimulus4":"<p style='font-size: 48px;'>TOOTH</p>","data":{"type":"distinct","category":"music","word":"TOOTH"},
"test":"<p style='font-size: 48px;'>SCARED</p>","data":{"type":"new","category":"music","test_type":"unrelated_test","word":"SCARED"}
},
{"stimulus1":"<p style='font-size: 48px;'>WINDOW</p>","data":{"type":"old","category":"buildingpart","word":"WINDOW"},
"stimulus2":"<p style='font-size: 48px;'>DOOR</p>","data":{"type":"old","category":"buildingpart","word":"DOOR"},
"stimulus3":"<p style='font-size: 48px;'>FLOOR</p>","data":{"type":"old","category":"buildingpart","word":"FLOOR"},
"stimulus4":"<p style='font-size: 48px;'>SHOCK</p>","data":{"type":"distinct","category":"buildingpart","word":"SHOCK"},
"test":"<p style='font-size: 48px;'>ATTEMPT</p>","data":{"type":"new","category":"buildingpart","test_type":"unrelated_test","word":"ATTEMPT"}
},
]