studywords = [
{
"stimulus1":"<p style='font-size: 48px;'>EAGLE</p>","data1":{"phase":"study","type":"old","category":"birds","word":"EAGLE"},
"stimulus2":"<p style='font-size: 48px;'>ROBIN</p>","data2":{"phase":"study","type":"old","category":"birds","word":"ROBIN"},
"stimulus3":"<p style='font-size: 48px;'>BLUEJAY</p>","data3":{"phase":"study","type":"old","category":"birds","word":"BLUEJAY"},
"stimulus4":"<p style='font-size: 48px;'>CONCEPT</p>","data4":{"phase":"study","type":"distinct","category":"birds","word":"CONCEPT"},

"test1":"<p style='font-size: 48px;'>EAGLE</p>","data5":{"phase":"test","type":"old","category":"birds","test_type":"cat_test","word":"EAGLE"},
"test2":"<p style='font-size: 48px;'>ROBIN</p>","data6":{"phase":"test","type":"old","category":"birds","test_type":"cat_test","word":"ROBIN"},
"test3":"<p style='font-size: 48px;'>BLUEJAY</p>","data7":{"phase":"test","type":"old","category":"birds","test_type":"cat_test","word":"BLUEJAY"},
"test4":"<p style='font-size: 48px;'>CONCEPT</p>","data8":{"phase":"test","type":"old","category":"birds","test_type":"distinct_test","word":"CONCEPT"},
"test5":"<p style='font-size: 48px;'>SALES</p>","data9":{"phase":"test","type":"new","category":"birds","test_type":"unrelated_test","word":"SALES"}, 
"test6":"<p style='font-size: 48px;'>MEAN</p>","data10":{"phase":"test","type":"new","category":"birds","test_type":"unrelated_test","word":"MEAN"},
"test7":"<p style='font-size: 48px;'>SERIES</p>","data11":{"phase":"test","type":"new","category":"birds","test_type":"unrelated_test","word":"SERIES"},
"test8":"<p style='font-size: 48px;'>DECORATE</p>","data12":{"phase":"test","type":"new","category":"birds","test_type":"unrelated_test","word":"DECORATE"},
},
{
"stimulus1":"<p style='font-size: 48px;'>BLUE</p>","data1":{"phase":"study","type":"old","category":"colors","word":"BLUE"},
"stimulus2":"<p style='font-size: 48px;'>RED</p>","data2":{"phase":"study","type":"old","category":"colors","word":"RED"},
"stimulus3":"<p style='font-size: 48px;'>GREEN</p>","data3":{"phase":"study","type":"old","category":"colors","word":"GREEN"},
"stimulus4":"<p style='font-size: 48px;'>TERRORISM</p>","data4":{"phase":"study","type":"distinct","category":"colors","word":"TERRORISM"},

"test1":"<p style='font-size: 48px;'>BLUE</p>","data5":{"phase":"test","type":"old","category":"colors","test_type":"cat_test","word":"BLUE"},
"test2":"<p style='font-size: 48px;'>RED</p>","data6":{"phase":"test","type":"old","category":"colors","test_type":"cat_test","word":"RED"},
"test3":"<p style='font-size: 48px;'>GREEN</p>","data7":{"phase":"test","type":"old","category":"colors","test_type":"cat_test","word":"GREEN"},
"test4":"<p style='font-size: 48px;'>TERRORISM</p>","data8":{"phase":"test","type":"old","category":"colors","test_type":"distinct_test","word":"TERRORISM"},
"test5":"<p style='font-size: 48px;'>COVER</p>","data9":{"phase":"test","type":"new","category":"colors","test_type":"unrelated_test","word":"COVER"},
"test6":"<p style='font-size: 48px;'>QUESTION</p>","data10":{"phase":"test","type":"new","category":"colors","test_type":"unrelated_test","word":"QUESTION"},
"test7":"<p style='font-size: 48px;'>TODAY</p>","data11":{"phase":"test","type":"new","category":"colors","test_type":"unrelated_test","word":"TODAY"},
"test8":"<p style='font-size: 48px;'>SKULL</p>","data12":{"phase":"test","type":"new","category":"colors","test_type":"unrelated_test","word":"SKULL"},
},
{
"stimulus1":"<p style='font-size: 48px;'>GASOLINE</p>","data1":{"phase":"study","type":"old","category":"fuel","word":"GASOLINE"},
"stimulus2":"<p style='font-size: 48px;'>DIESEL</p>","data2":{"phase":"study","type":"old","category":"fuel","word":"DIESEL"},
"stimulus3":"<p style='font-size: 48px;'>OIL</p>","data3":{"phase":"study","type":"old","category":"fuel","word":"OIL"},
"stimulus4":"<p style='font-size: 48px;'>GATHER</p>","data4":{"phase":"study","type":"distinct","category":"fuel","word":"GATHER"},

"test1":"<p style='font-size: 48px;'>GASOLINE</p>","data5":{"phase":"test","type":"old","category":"fuel","test_type":"cat_test","word":"GASOLINE"},
"test2":"<p style='font-size: 48px;'>DIESEL</p>","data6":{"phase":"test","type":"old","category":"fuel","test_type":"cat_test","word":"DIESEL"},
"test3":"<p style='font-size: 48px;'>OIL</p>","data7":{"phase":"test","type":"old","category":"fuel","test_type":"cat_test","word":"OIL"},
"test4":"<p style='font-size: 48px;'>GATHER</p>","data8":{"phase":"test","type":"old", "category":"fuel","test_type":"distinct_test","word":"GATHER"},
"test5":"<p style='font-size: 48px;'>GRANDPARENT</p>","data9":{"phase":"test","type":"new","category":"fuel","test_type":"unrelated_test","word":"GRANDPARENT"},
"test6":"<p style='font-size: 48px;'>HALF</p>","data10":{"phase":"test","type":"new","category":"fuel","test_type":"unrelated_test","word":"HALF"},
"test7":"<p style='font-size: 48px;'>CANCEL</p>","data11":{"phase":"test","type":"new","category":"fuel","test_type":"unrelated_test","word":"CANCEL"},
"test8":"<p style='font-size: 48px;'>QUICKLY</p>","data12":{"phase":"test","type":"new","category":"fuel","test_type":"unrelated_test","word":"QUICKLY"},
},
{
"stimulus1":"<p style='font-size: 48px;'>HOUSE</p>","data1":{"phase":"study","type":"old","category":"dwelling","word":"HOUSE"},
"stimulus2":"<p style='font-size: 48px;'>APARTMENT</p>","data2":{"phase":"study","type":"old","category":"dwelling","word":"APARTMENT"},
"stimulus3":"<p style='font-size: 48px;'>MANSION</p>","data3":{"phase":"study","type":"old","category":"dwelling","word":"MANSION"},
"stimulus4":"<p style='font-size: 48px;'>HIRE</p>","data4":{"phase":"study","type":"distinct","category":"dwelling","word":"HIRE"},

"test1":"<p style='font-size: 48px;'>HOUSE</p>","data5":{"phase":"test","type":"old","category":"dwelling","test_type":"cat_test","word":"HOUSE"},
"test2":"<p style='font-size: 48px;'>APARTMENT</p>","data6":{"phase":"test","type":"old","category":"dwelling","test_type":"cat_test","word":"APARTMENT"},
"test3":"<p style='font-size: 48px;'>MANSION</p>","data7":{"phase":"test","type":"old","category":"dwelling","test_type":"cat_test","word":"MANSION"},
"test4":"<p style='font-size: 48px;'>HIRE</p>","data8":{"phase":"test","type":"old","category":"dwelling","test_type":"distinct_test","word":"HIRE"},
"test5":"<p style='font-size: 48px;'>MYTH</p>","data9":{"phase":"test","type":"new","category":"dwelling","test_type":"unrelated_test","word":"MYTH"},
"test6":"<p style='font-size: 48px;'>ENGLISH</p>","data10":{"phase":"test","type":"new","category":"dwelling","test_type":"unrelated_test","word":"ENGLISH"},
"test7":"<p style='font-size: 48px;'>MACHINE</p>","data11":{"phase":"test","type":"new","category":"dwelling","test_type":"unrelated_test","word":"MACHINE"},
"test8":"<p style='font-size: 48px;'>ICON</p>","data12":{"phase":"test","type":"new","category":"dwelling","test_type":"unrelated_test","word":"ICON"},
},
{"stimulus1":"<p style='font-size: 48px;'>FOOTBALL</p>","data1":{"phase":"study","type":"old","category":"sports","word":"FOOTBALL"},
"stimulus2":"<p style='font-size: 48px;'>BASKETBALL</p>","data2":{"phase":"study","type":"old","category":"sports","word":"BASKETBALL"},
"stimulus3":"<p style='font-size: 48px;'>SOCCER</p>","data3":{"phase":"study","type":"old","category":"sports","word":"SOCCER"},
"stimulus4":"<p style='font-size: 48px;'>KNOW</p>","data4":{"phase":"study","type":"distinct","category":"sports","word":"KNOW"},

"test1":"<p style='font-size: 48px;'>FOOTBALL</p>","data5":{"phase":"test","type":"old","category":"sports","test_type":"cat_test","word":"FOOTBALL"},
"test2":"<p style='font-size: 48px;'>BASKETBALL</p>","data6":{"phase":"test","type":"old","category":"sports","test_type":"cat_test","word":"BASKETBALL"},
"test3":"<p style='font-size: 48px;'>SOCCER</p>","data7":{"phase":"test","type":"old","category":"sports","test_type":"cat_test","word":"SOCCER"},
"test4":"<p style='font-size: 48px;'>KNOW</p>","data8":{"phase":"test","type":"old","category":"sports","test_type":"distinct_test","word":"KNOW"},
"test5":"<p style='font-size: 48px;'>PUNISH</p>","data9":{"phase":"test","type":"new","category":"sports","test_type":"unrelated_test","word":"PUNISH"},
"test6":"<p style='font-size: 48px;'>ARGUMENT</p>","data10":{"phase":"test","type":"new","category":"sports","test_type":"unrelated_test","word":"ARGUMENT"},
"test7":"<p style='font-size: 48px;'>ASSURE</p>","data11":{"phase":"test","type":"new","category":"sports","test_type":"unrelated_test","word":"ASSURE"},
"test8":"<p style='font-size: 48px;'>METAPHOR</p>","data12":{"phase":"test","type":"new","category":"sports","test_type":"unrelated_test","word":"METAPHOR"},
},
{"stimulus1":"<p style='font-size: 48px;'>MAGAZINE</p>","data1":{"phase":"study","type":"old","category":"reading","word":"MAGAZINE"},
"stimulus2":"<p style='font-size: 48px;'>BOOK</p>","data2":{"phase":"study","type":"old","category":"reading","word":"BOOK"},
"stimulus3":"<p style='font-size: 48px;'>NEWSPAPER</p>","data3":{"phase":"study","type":"old","category":"reading","word":"NEWSPAPER"},
"stimulus4":"<p style='font-size: 48px;'>TRAILER</p>","data4":{"phase":"study","type":"distinct","category":"reading","word":"TRAILER"},

"test1":"<p style='font-size: 48px;'>MAGAZINE</p>","data5":{"phase":"test","type":"old","category":"reading","test_type":"cat_test","word":"MAGAZINE"},
"test2":"<p style='font-size: 48px;'>BOOK</p>","data6":{"phase":"test","type":"old","category":"reading","test_type":"cat_test","word":"BOOK"},
"test3":"<p style='font-size: 48px;'>NEWSPAPER</p>","data7":{"phase":"test","type":"old","category":"reading","test_type":"cat_test","word":"NEWSPAPER"},
"test4":"<p style='font-size: 48px;'>TRAILER</p>","data8":{"phase":"test","type":"old","category":"reading","test_type":"distinct_test","word":"TRAILER"},
"test5":"<p style='font-size: 48px;'>ABSOLUTELY</p>","data9":{"phase":"test","type":"new","category":"reading","test_type":"unrelated_test","word":"ABSOLUTELY"},
"test6":"<p style='font-size: 48px;'>PHSYICALLY</p>","data10":{"phase":"test","type":"new","category":"reading","test_type":"unrelated_test","word":"PHSYICALLY"},
"test7":"<p style='font-size: 48px;'>ACTIVELY</p>","data11":{"phase":"test","type":"new","category":"reading","test_type":"unrelated_test","word":"ACTIVELY"},
"test8":"<p style='font-size: 48px;'>NORTHERN</p>","data12":{"phase":"test","type":"new","category":"reading","test_type":"unrelated_test","word":"NORTHERN"},
},
{"stimulus1":"<p style='font-size: 48px;'>KNIFE</p>","data1":{"phase":"study","type":"old","category":"utensil","word":"KNIFE"},
"stimulus2":"<p style='font-size: 48px;'>FORK</p>","data2":{"phase":"study","type":"old","category":"utensil","word":"FORK"},
"stimulus3":"<p style='font-size: 48px;'>SPOON</p>","data3":{"phase":"study","type":"old","category":"utensil","word":"SPOON"},
"stimulus4":"<p style='font-size: 48px;'>BOLD</p>","data4":{"phase":"study","type":"distinct","category":"utensil","word":"BOLD"},

"test1":"<p style='font-size: 48px;'>KNIFE</p>","data5":{"phase":"test","type":"old","category":"utensil","test_type":"cat_test","word":"KNIFE"},
"test2":"<p style='font-size: 48px;'>FORK</p>","data6":{"phase":"test","type":"old","category":"utensil","test_type":"cat_test","word":"FORK"},
"test3":"<p style='font-size: 48px;'>SPOON</p>","data7":{"phase":"test","type":"old","category":"utensil","test_type":"cat_test","word":"SPOON"},
"test4":"<p style='font-size: 48px;'>BOLD</p>","data8":{"phase":"test","type":"old","category":"utensil","test_type":"distinct_test","word":"BOLD"},
"test5":"<p style='font-size: 48px;'>STRUCTURE</p>","data9":{"phase":"test","type":"new","category":"utensil","test_type":"unrelated_test","word":"STRUCTURE"},
"test6":"<p style='font-size: 48px;'>HOSTILE</p>","data10":{"phase":"test","type":"new","category":"utensil","test_type":"unrelated_test","word":"HOSTILE"},
"test7":"<p style='font-size: 48px;'>MERIT</p>","data11":{"phase":"test","type":"new","category":"utensil","test_type":"unrelated_test","word":"MERIT"},
"test8":"<p style='font-size: 48px;'>FIXED</p>","data12":{"phase":"test","type":"new","category":"utensil","test_type":"unrelated_test","word":"FIXED"},
},
{"stimulus1":"<p style='font-size: 48px;'>NOUN</p>","data1":{"phase":"study","type":"old","category":"speech","word":"NOUN"},
"stimulus2":"<p style='font-size: 48px;'>VERB</p>","data2":{"phase":"study","type":"old","category":"speech","word":"VERB"},
"stimulus3":"<p style='font-size: 48px;'>ADJECTIVE</p>","data3":{"phase":"study","type":"old","category":"speech","word":"ADJECTIVE"},
"stimulus4":"<p style='font-size: 48px;'>TENDENCY</p>","data4":{"phase":"study","type":"distinct","category":"speech","word":"TENDENCY"},

"test1":"<p style='font-size: 48px;'>NOUN</p>","data5":{"phase":"test","type":"old","category":"speech","test_type":"cat_test","word":"NOUN"},
"test2":"<p style='font-size: 48px;'>VERB</p>","data6":{"phase":"test","type":"old","category":"speech","test_type":"cat_test","word":"VERB"},
"test3":"<p style='font-size: 48px;'>ADJECTIVE</p>","data7":{"phase":"test","type":"old","category":"speech","test_type":"cat_test","word":"ADJECTIVE"},
"test4":"<p style='font-size: 48px;'>TENDENCY</p>","data8":{"phase":"test","type":"old","category":"speech","test_type":"distinct_test","word":"TENDENCY"},
"test5":"<p style='font-size: 48px;'>LEGISLATURE</p>","data9":{"phase":"test","type":"new","category":"speech","test_type":"unrelated_test","word":"LEGISLATURE"},
"test6":"<p style='font-size: 48px;'>MARRIAGE</p>","data10":{"phase":"test","type":"new","category":"speech","test_type":"unrelated_test","word":"MARRIAGE"},
"test7":"<p style='font-size: 48px;'>USED</p>","data11":{"phase":"test","type":"new","category":"speech","test_type":"unrelated_test","word":"USED"},
"test8":"<p style='font-size: 48px;'>SIGNAL</p>","data12":{"phase":"test","type":"new","category":"speech","test_type":"unrelated_test","word":"SIGNAL"},
},
{"stimulus1":"<p style='font-size: 48px;'>DOLLAR</p>","data1":{"phase":"study","type":"old","category":"money","word":"DOLLAR"},
"stimulus2":"<p style='font-size: 48px;'>CENT</p>","data2":{"phase":"study","type":"old","category":"money","word":"CENT"},
"stimulus3":"<p style='font-size: 48px;'>DIME</p>","data3":{"phase":"study","type":"old","category":"money","word":"DIME"},
"stimulus4":"<p style='font-size: 48px;'>ROUTE</p>","data4":{"phase":"study","type":"distinct","category":"money","word":"ROUTE"},

"test1":"<p style='font-size: 48px;'>DOLLAR</p>","data5":{"phase":"test","type":"old","category":"money","test_type":"cat_test","word":"DOLLAR"},
"test2":"<p style='font-size: 48px;'>CENT</p>","data6":{"phase":"test","type":"old","category":"money","test_type":"cat_test","word":"CENT"},
"test3":"<p style='font-size: 48px;'>DIME</p>","data7":{"phase":"test","type":"old","category":"money","test_type":"cat_test","word":"DIME"},
"test4":"<p style='font-size: 48px;'>ROUTE</p>","data8":{"phase":"test","type":"old","category":"money","test_type":"distinct_test","word":"ROUTE"},
"test5":"<p style='font-size: 48px;'>BEGINNING</p>","data9":{"phase":"test","type":"new","category":"money","test_type":"unrelated_test","word":"BEGINNING"},
"test6":"<p style='font-size: 48px;'>PRESSURE</p>","data10":{"phase":"test","type":"new","category":"money","test_type":"unrelated_test","word":"PRESSURE"},
"test7":"<p style='font-size: 48px;'>SUE</p>","data11":{"phase":"test","type":"new","category":"money","test_type":"unrelated_test","word":"SUE"},
"test8":"<p style='font-size: 48px;'>BIRTHDAY</p>","data12":{"phase":"test","type":"new","category":"money","test_type":"unrelated_test","word":"BIRTHDAY"},
},
{"stimulus1":"<p style='font-size: 48px;'>HAMMER</p>","data1":{"phase":"study","type":"old","category":"tool","word":"HAMMER"},
"stimulus2":"<p style='font-size: 48px;'>NAIL</p>","data2":{"phase":"study","type":"old","category":"tool","word":"NAIL"},
"stimulus3":"<p style='font-size: 48px;'>SAW</p>","data3":{"phase":"study","type":"old","category":"tool","word":"SAW"},
"stimulus4":"<p style='font-size: 48px;'>INDEPENDENT</p>","data4":{"phase":"study","type":"distinct","category":"tool","word":"INDEPENDENT"},

"test1":"<p style='font-size: 48px;'>HAMMER</p>","data5":{"phase":"test","type":"old","category":"tool","test_type":"cat_test","word":"HAMMER"},
"test2":"<p style='font-size: 48px;'>NAIL</p>","data6":{"phase":"test","type":"old","category":"tool","test_type":"cat_test","word":"NAIL"},
"test3":"<p style='font-size: 48px;'>SAW</p>","data7":{"phase":"test","type":"old","category":"tool","test_type":"cat_test","word":"SAW"},
"test4":"<p style='font-size: 48px;'>INDEPENDENT</p>","data8":{"phase":"test","type":"old","category":"tool","test_type":"distinct_test","word":"INDEPENDENT"},
"test5":"<p style='font-size: 48px;'>CURIOUS</p>","data9":{"phase":"test","type":"new","category":"tool","test_type":"unrelated_test","word":"CURIOUS"},
"test6":"<p style='font-size: 48px;'>CENTER</p>","data10":{"phase":"test","type":"new","category":"tool","test_type":"unrelated_test","word":"CENTER"},
"test7":"<p style='font-size: 48px;'>PRIZE</p>","data11":{"phase":"test","type":"new","category":"tool","test_type":"unrelated_test","word":"PRIZE"},
"test8":"<p style='font-size: 48px;'>TRANSFER</p>","data12":{"phase":"test","type":"new","category":"tool","test_type":"unrelated_test","word":"TRANSFER"},
},
{"stimulus1":"<p style='font-size: 48px;'>AMERICA</p>","data1":{"phase":"study","type":"old","category":"country","word":"AMERICA"},
"stimulus2":"<p style='font-size: 48px;'>CANADA</p>","data2":{"phase":"study","type":"old","category":"country","word":"CANADA"},
"stimulus3":"<p style='font-size: 48px;'>FRANCE</p>","data3":{"phase":"study","type":"old","category":"country","word":"FRANCE"},
"stimulus4":"<p style='font-size: 48px;'>SPECIAL</p>","data4":{"phase":"study","type":"distinct","category":"country","word":"SPECIAL"},

"test1":"<p style='font-size: 48px;'>AMERICA</p>","data5":{"phase":"test","type":"old","category":"country","test_type":"cat_test","word":"AMERICA"},
"test2":"<p style='font-size: 48px;'>CANADA</p>","data6":{"phase":"test","type":"old","category":"country","test_type":"cat_test","word":"CANADA"},
"test3":"<p style='font-size: 48px;'>FRANCE</p>","data7":{"phase":"test","type":"old","category":"country","test_type":"cat_test","word":"FRANCE"},
"test4":"<p style='font-size: 48px;'>SPECIAL</p>","data8":{"phase":"test","type":"old","category":"country","test_type":"distinct_test","word":"SPECIAL"},
"test5":"<p style='font-size: 48px;'>IMPLEMENT</p>","data9":{"phase":"test","type":"new","category":"country","test_type":"unrelated_test","word":"IMPLEMENT"},
"test6":"<p style='font-size: 48px;'>SCARED</p>","data10":{"phase":"test","type":"new","category":"country","test_type":"unrelated_test","word":"SCARED"},
"test7":"<p style='font-size: 48px;'>SHOVE</p>","data11":{"phase":"test","type":"new","category":"country","test_type":"unrelated_test","word":"SHOVE"},
"test8":"<p style='font-size: 48px;'>DISAPPEAR</p>","data12":{"phase":"test","type":"new","category":"country","test_type":"unrelated_test","word":"DISAPPEAR"},
},
{"stimulus1":"<p style='font-size: 48px;'>OXYGEN</p>","data1":{"phase":"study","type":"old","category":"element","word":"OXYGEN"},
"stimulus2":"<p style='font-size: 48px;'>HYDROGEN</p>","data2":{"phase":"study","type":"old","category":"element","word":"HYDROGEN"},
"stimulus3":"<p style='font-size: 48px;'>CARBON</p>","data3":{"phase":"study","type":"old","category":"element","word":"CARBON"},
"stimulus4":"<p style='font-size: 48px;'>CHIEF</p>","data4":{"phase":"study","type":"distinct","category":"element","word":"CHIEF"},

"test1":"<p style='font-size: 48px;'>OXYGEN</p>","data5":{"phase":"test","type":"old","category":"element","test_type":"cat_test","word":"OXYGEN"},
"test2":"<p style='font-size: 48px;'>HYDROGEN</p>","data6":{"phase":"test","type":"old","category":"element","test_type":"cat_test","word":"HYDROGEN"},
"test3":"<p style='font-size: 48px;'>CARBON</p>","data7":{"phase":"test","type":"old","category":"element","test_type":"cat_test","word":"CARBON"},
"test4":"<p style='font-size: 48px;'>CHIEF</p>","data8":{"phase":"test","type":"old","category":"element","test_type":"distinct_test","word":"CHIEF"},
"test5":"<p style='font-size: 48px;'>THIGH</p>","data9":{"phase":"test","type":"new","category":"element","test_type":"unrelated_test","word":"THIGH"},
"test6":"<p style='font-size: 48px;'>ATTEMPT</p>","data10":{"phase":"test","type":"new","category":"element","test_type":"unrelated_test","word":"ATTEMPT"},
"test7":"<p style='font-size: 48px;'>TEMPORARY</p>","data11":{"phase":"test","type":"new","category":"element","test_type":"unrelated_test","word":"TEMPORARY"},
"test8":"<p style='font-size: 48px;'>MINORITY</p>","data12":{"phase":"test","type":"new","category":"element","test_type":"unrelated_test","word":"MINORITY"},
},
{"stimulus1":"<p style='font-size: 48px;'>SHIRT</p>","data1":{"phase":"study","type":"old","category":"clothing","word":"SHIRT"},
"stimulus2":"<p style='font-size: 48px;'>PANTS</p>","data2":{"phase":"study","type":"old","category":"clothing","word":"PANTS"},
"stimulus3":"<p style='font-size: 48px;'>SOCKS</p>","data3":{"phase":"study","type":"old","category":"clothing","word":"SOCKS"},
"stimulus4":"<p style='font-size: 48px;'>ELIGIBLE</p>","data4":{"phase":"study","type":"distinct","category":"clothing","word":"ELIGIBLE"},

"test1":"<p style='font-size: 48px;'>SHIRT</p>","data5":{"phase":"test","type":"old","category":"clothing","test_type":"cat_test","word":"SHIRT"},
"test2":"<p style='font-size: 48px;'>PANTS</p>","data6":{"phase":"test","type":"old","category":"clothing","test_type":"cat_test","word":"PANTS"},
"test3":"<p style='font-size: 48px;'>SOCKS</p>","data7":{"phase":"test","type":"old","category":"clothing","test_type":"cat_test","word":"SOCKS"},
"test4":"<p style='font-size: 48px;'>ELIGIBLE</p>","data8":{"phase":"test","type":"old","category":"clothing","test_type":"distinct_test","word":"ELIGIBLE"},
"test5":"<p style='font-size: 48px;'>FURTHERMORE</p>","data9":{"phase":"test","type":"new","category":"clothing","test_type":"unrelated_test","word":"FURTHERMORE"},
"test6":"<p style='font-size: 48px;'>SOCIETY</p>","data10":{"phase":"test","type":"new","category":"clothing","test_type":"unrelated_test","word":"SOCIETY"},
"test7":"<p style='font-size: 48px;'>MALE</p>","data11":{"phase":"test","type":"new","category":"clothing","test_type":"unrelated_test","word":"MALE"},
"test8":"<p style='font-size: 48px;'>LIBERTY</p>","data12":{"phase":"test","type":"new","category":"clothing","test_type":"unrelated_test","word":"LIBERTY"},
},
{"stimulus1":"<p style='font-size: 48px;'>DRUMS</p>","data1":{"phase":"study","type":"old","category":"instrument","word":"DRUMS"},
"stimulus2":"<p style='font-size: 48px;'>GUITAR</p>","data2":{"phase":"study","type":"old","category":"instrument","word":"GUITAR"},
"stimulus3":"<p style='font-size: 48px;'>FLUTE</p>","data3":{"phase":"study","type":"old","category":"instrument","word":"FLUTE"},
"stimulus4":"<p style='font-size: 48px;'>SPOT</p>","data4":{"phase":"study","type":"distinct","category":"instrument","word":"SPOT"},

"test1":"<p style='font-size: 48px;'>DRUMS</p>","data5":{"phase":"test","type":"old","category":"instrument","test_type":"cat_test","word":"DRUMS"},
"test2":"<p style='font-size: 48px;'>GUITAR</p>","data6":{"phase":"test","type":"old","category":"instrument","test_type":"cat_test","word":"GUITAR"},
"test3":"<p style='font-size: 48px;'>FLUTE</p>","data7":{"phase":"test","type":"old","category":"instrument","test_type":"cat_test","word":"FLUTE"},
"test4":"<p style='font-size: 48px;'>SPOT</p>","data8":{"phase":"test","type":"old","category":"instrument","test_type":"distinct_test","word":"SPOT"},
"test5":"<p style='font-size: 48px;'>TYPICALLY</p>","data9":{"phase":"test","type":"new","category":"instrument","test_type":"unrelated_test","word":"TYPICALLY"},
"test6":"<p style='font-size: 48px;'>NATIONAL</p>","data10":{"phase":"test","type":"new","category":"instrument","test_type":"unrelated_test","word":"NATIONAL"},
"test7":"<p style='font-size: 48px;'>SURELY</p>","data11":{"phase":"test","type":"new","category":"instrument","test_type":"unrelated_test","word":"SURELY"},
"test8":"<p style='font-size: 48px;'>COMPRISE</p>","data12":{"phase":"test","type":"new","category":"instrument","test_type":"unrelated_test","word":"COMPRISE"},
},
{"stimulus1":"<p style='font-size: 48px;'>DIAMOND</p>","data1":{"phase":"study","type":"old","category":"stone","word":"DIAMOND"},
"stimulus2":"<p style='font-size: 48px;'>RUBY</p>","data2":{"phase":"study","type":"old","category":"stone","word":"RUBY"},
"stimulus3":"<p style='font-size: 48px;'>EMERALD</p>","data3":{"phase":"study","type":"old","category":"stone","word":"EMERALD"},
"stimulus4":"<p style='font-size: 48px;'>WRITING</p>","data4":{"phase":"study","type":"distinct","category":"stone","word":"WRITING"},

"test1":"<p style='font-size: 48px;'>DIAMOND</p>","data5":{"phase":"test","type":"old","category":"stone","test_type":"cat_test","word":"DIAMOND"},
"test2":"<p style='font-size: 48px;'>RUBY</p>","data6":{"phase":"test","type":"old","category":"stone","test_type":"cat_test","word":"RUBY"},
"test3":"<p style='font-size: 48px;'>EMERALD</p>","data7":{"phase":"test","type":"old","category":"stone","test_type":"cat_test","word":"EMERALD"},
"test4":"<p style='font-size: 48px;'>WRITING</p>","data8":{"phase":"test","type":"old","category":"stone","test_type":"distinct_test","word":">WRITING"},
"test5":"<p style='font-size: 48px;'>LIMITED</p>","data9":{"phase":"test","type":"new","category":"stone","test_type":"unrelated_test","word":"LIMITED"},
"test6":"<p style='font-size: 48px;'>CONSENSUS</p>","data10":{"phase":"test","type":"new","category":"stone","test_type":"unrelated_test","word":"CONSENSUS"},
"test7":"<p style='font-size: 48px;'>EXPECTED</p>","data11":{"phase":"test","type":"new","category":"stone","test_type":"unrelated_test","word":"EXPECTED"},
"test8":"<p style='font-size: 48px;'>GLOBE</p>","data12":{"phase":"test","type":"new","category":"stone","test_type":"unrelated_test","word":"GLOBE"},
},
{"stimulus1":"<p style='font-size: 48px;'>OAK</p>","data1":{"phase":"study","type":"old","category":"tree","word":"OAK"},
"stimulus2":"<p style='font-size: 48px;'>PINE</p>","data2":{"phase":"study","type":"old","category":"tree","word":"PINE"},
"stimulus3":"<p style='font-size: 48px;'>MAPLE</p>","data3":{"phase":"study","type":"old","category":"tree","word":"MAPLE"},
"stimulus4":"<p style='font-size: 48px;'>RESPONSIBLE</p>","data4":{"phase":"study","type":"distinct","category":"tree","word":"RESPONSIBLE"},

"test1":"<p style='font-size: 48px;'>OAK</p>","data5":{"phase":"test","type":"old","category":"tree","test_type":"cat_test","word":"OAK"},
"test2":"<p style='font-size: 48px;'>PINE</p>","data6":{"phase":"test","type":"old","category":"tree","test_type":"cat_test","word":"PINE"},
"test3":"<p style='font-size: 48px;'>MAPLE</p>","data7":{"phase":"test","type":"old","category":"tree","test_type":"cat_test","word":"MAPLE"},
"test4":"<p style='font-size: 48px;'>RESPONSIBLE</p>","data8":{"phase":"test","type":"old","category":"tree","test_type":"distinct_test","word":"RESPONSIBLE"},
"test5":"<p style='font-size: 48px;'>FAITH</p>","data9":{"phase":"test","type":"new","category":"tree","test_type":"unrelated_test","word":"FAITH"},
"test6":"<p style='font-size: 48px;'>LINE</p>","data10":{"phase":"test","type":"new","category":"tree","test_type":"unrelated_test","word":"LINE"},
"test7":"<p style='font-size: 48px;'>SCHOLAR</p>","data11":{"phase":"test","type":"new","category":"tree","test_type":"unrelated_test","word":"SCHOLAR"},
"test8":"<p style='font-size: 48px;'>INCREASINGLY</p>","data12":{"phase":"test","type":"new","category":"tree","test_type":"unrelated_test","word":"INCREASINGLY"},
},
{"stimulus1":"<p style='font-size: 48px;'>BALLET</p>","data1":{"phase":"study","type":"old","category":"dance","word":"BALLET"},
"stimulus2":"<p style='font-size: 48px;'>TANGO</p>","data2":{"phase":"study","type":"old","category":"dance","word":"TANGO"},
"stimulus3":"<p style='font-size: 48px;'>SALSA</p>","data3":{"phase":"study","type":"old","category":"dance","word":"SALSA"},
"stimulus4":"<p style='font-size: 48px;'>PEASANT</p>","data4":{"phase":"study","type":"distinct","category":"dance","word":"PEASANT"},

"test1":"<p style='font-size: 48px;'>BALLET</p>","data5":{"phase":"test","type":"old","category":"dance","test_type":"cat_test","word":"BALLET"},
"test2":"<p style='font-size: 48px;'>TANGO</p>","data6":{"phase":"test","type":"old","category":"dance","test_type":"cat_test","word":"TANGO"},
"test3":"<p style='font-size: 48px;'>SALSA</p>","data7":{"phase":"test","type":"old","category":"dance","test_type":"cat_test","word":"SALSA"},
"test4":"<p style='font-size: 48px;'>PEASANT</p>","data8":{"phase":"test","type":"old","category":"dance","test_type":"distinct_test","word":"PEASANT"},
"test5":"<p style='font-size: 48px;'>IMPORTANT</p>","data9":{"phase":"test","type":"new","category":"dance","test_type":"unrelated_test","word":"IMPORTANT"},
"test6":"<p style='font-size: 48px;'>WAY</p>","data10":{"phase":"test","type":"new","category":"dance","test_type":"unrelated_test","word":"WAY"},
"test7":"<p style='font-size: 48px;'>PRIDE</p>","data11":{"phase":"test","type":"new","category":"dance","test_type":"unrelated_test","word":"PRIDE"},
"test8":"<p style='font-size: 48px;'>AWAKE</p>","data12":{"phase":"test","type":"new","category":"dance","test_type":"unrelated_test","word":"AWAKE"},
},
{"stimulus1":"<p style='font-size: 48px;'>CHAIR</p>","data1":{"phase":"study","type":"old","category":"furniture","word":"CHAIR"},
"stimulus2":"<p style='font-size: 48px;'>TABLE</p>","data2":{"phase":"study","type":"old","category":"furniture","word":"TABLE"},
"stimulus3":"<p style='font-size: 48px;'>COUCH</p>","data3":{"phase":"study","type":"old","category":"furniture","word":"COUCH"},
"stimulus4":"<p style='font-size: 48px;'>DISK</p>","data4":{"phase":"study","type":"distinct","category":"furniture","word":"DISK"},

"test1":"<p style='font-size: 48px;'>CHAIR</p>","data5":{"phase":"test","type":"old","category":"furniture","test_type":"cat_test","word":"CHAIR"},
"test2":"<p style='font-size: 48px;'>TABLE</p>","data6":{"phase":"test","type":"old","category":"furniture","test_type":"cat_test","word":"TABLE"},
"test3":"<p style='font-size: 48px;'>COUCH</p>","data7":{"phase":"test","type":"old","category":"furniture","test_type":"cat_test","word":"COUCH"},
"test4":"<p style='font-size: 48px;'>DISK</p>","data8":{"phase":"test","type":"old","category":"furniture","test_type":"distinct_test","word":"DISK"},
"test5":"<p style='font-size: 48px;'>SETTING</p>","data9":{"phase":"test","type":"new","category":"furniture","test_type":"unrelated_test","word":"SETTING"},
"test6":"<p style='font-size: 48px;'>HARD</p>","data10":{"phase":"test","type":"new","category":"furniture","test_type":"unrelated_test","word":"HARD"},
"test7":"<p style='font-size: 48px;'>COOPERATE</p>","data11":{"phase":"test","type":"new","category":"furniture","test_type":"unrelated_test","word":"COOPERATE"},
"test8":"<p style='font-size: 48px;'>EXPERIENCE</p>","data12":{"phase":"test","type":"new","category":"furniture","test_type":"unrelated_test","word":"EXPERIENCE"},
},
{"stimulus1":"<p style='font-size: 48px;'>DOCTOR</p>","data1":{"phase":"study","type":"old","category":"profession","word":"DOCTOR"},
"stimulus2":"<p style='font-size: 48px;'>TEACHER</p>","data2":{"phase":"study","type":"old","category":"profession","word":"TEACHER"},
"stimulus3":"<p style='font-size: 48px;'>LAWYER</p>","data3":{"phase":"study","type":"old","category":"profession","word":"LAWYER"},
"stimulus4":"<p style='font-size: 48px;'>INVISIBLE</p>","data4":{"phase":"study","type":"distinct","category":"profession","word":"INVISIBLE"},

"test1":"<p style='font-size: 48px;'>DOCTOR</p>","data5":{"phase":"test","type":"old","category":"profession","test_type":"cat_test","word":"DOCTOR"},
"test2":"<p style='font-size: 48px;'>TEACHER</p>","data6":{"phase":"test","type":"old","category":"profession","test_type":"cat_test","word":"TEACHER"},
"test3":"<p style='font-size: 48px;'>LAWYER</p>","data7":{"phase":"test","type":"old","category":"profession","test_type":"cat_test","word":"LAWYER"},
"test4":"<p style='font-size: 48px;'>INVISIBLE</p>","data8":{"phase":"test","type":"old","category":"profession","test_type":"distinct_test","word":"INVISIBLE"},
"test5":"<p style='font-size: 48px;'>IGNORE</p>","data9":{"phase":"test","type":"new","category":"profession","test_type":"unrelated_test","word":"IGNORE"},
"test6":"<p style='font-size: 48px;'>PASS</p>","data10":{"phase":"test","type":"new","category":"profession","test_type":"unrelated_test","word":"PASS"},
"test7":"<p style='font-size: 48px;'>ROYAL</p>","data11":{"phase":"test","type":"new","category":"profession","test_type":"unrelated_test","word":"ROYAL"},
"test8":"<p style='font-size: 48px;'>SNEAK</p>","data12":{"phase":"test","type":"new","category":"profession","test_type":"unrelated_test","word":"SNEAK"},
},
{"stimulus1":"<p style='font-size: 48px;'>MOUNTAIN</p>","data1":{"phase":"study","type":"old","category":"earth","word":"MOUNTAIN"},
"stimulus2":"<p style='font-size: 48px;'>RIVER</p>","data2":{"phase":"study","type":"old","category":"earth","word":"RIVER"},
"stimulus3":"<p style='font-size: 48px;'>OCEAN</p>","data3":{"phase":"study","type":"old","category":"earth","word":"OCEAN"},
"stimulus4":"<p style='font-size: 48px;'>ENORMOUS</p>","data4":{"phase":"study","type":"distinct","category":"earth","word":"ENORMOUS"},

"test1":"<p style='font-size: 48px;'>MOUNTAIN</p>","data5":{"phase":"test","type":"old","category":"earth","test_type":"cat_test","word":"MOUNTAIN"},
"test2":"<p style='font-size: 48px;'>RIVER</p>","data6":{"phase":"test","type":"old","category":"earth","test_type":"cat_test","word":"RIVER"},
"test3":"<p style='font-size: 48px;'>OCEAN</p>","data7":{"phase":"test","type":"old","category":"earth","test_type":"cat_test","word":"OCEAN"},
"test4":"<p style='font-size: 48px;'>ENORMOUS</p>","data8":{"phase":"test","type":"old","category":"earth","test_type":"distinct_test","word":"ENORMOUS"},
"test5":"<p style='font-size: 48px;'>PILE</p>","data9":{"phase":"test","type":"new","category":"earth","test_type":"unrelated_test","word":"PILE"},
"test6":"<p style='font-size: 48px;'>OLD</p>","data10":{"phase":"test","type":"new","category":"earth","test_type":"unrelated_test","word":"OLD"},
"test7":"<p style='font-size: 48px;'>TROUBLED</p>","data11":{"phase":"test","type":"new","category":"earth","test_type":"unrelated_test","word":"TROUBLED"},
"test8":"<p style='font-size: 48px;'>COMMENT</p>","data12":{"phase":"test","type":"new","category":"earth","test_type":"unrelated_test","word":"COMMENT"},
},
{"stimulus1":"<p style='font-size: 48px;'>APPLE</p>","data1":{"phase":"study","type":"old","category":"fruit","word":"APPLE"},
"stimulus2":"<p style='font-size: 48px;'>ORANGE</p>","data2":{"phase":"study","type":"old","category":"fruit","word":"ORANGE"},
"stimulus3":"<p style='font-size: 48px;'>BANANA</p>","data3":{"phase":"study","type":"old","category":"fruit","word":"BANANA"},
"stimulus4":"<p style='font-size: 48px;'>SUBSIDY</p>","data4":{"phase":"study","type":"distinct","category":"fruit","word":"SUBSIDY"},

"test1":"<p style='font-size: 48px;'>APPLE</p>","data5":{"phase":"test","type":"old","category":"fruit","test_type":"cat_test","word":"APPLE"},
"test2":"<p style='font-size: 48px;'>ORANGE</p>","data6":{"phase":"test","type":"old","category":"fruit","test_type":"cat_test","word":"ORANGE"},
"test3":"<p style='font-size: 48px;'>BANANA</p>","data7":{"phase":"test","type":"old","category":"fruit","test_type":"cat_test","word":"BANANA"},
"test4":"<p style='font-size: 48px;'>SUBSIDY</p>","data8":{"phase":"test","type":"old","category":"fruit","test_type":"distinct_test","word":"SUBSIDY"},
"test5":"<p style='font-size: 48px;'>GUIDELINE</p>","data9":{"phase":"test","type":"new","category":"fruit","test_type":"unrelated_test","word":"GUIDELINE"},
"test6":"<p style='font-size: 48px;'>SPECULATION</p>","data10":{"phase":"test","type":"new","category":"fruit","test_type":"unrelated_test","word":"SPECULATION"},
"test7":"<p style='font-size: 48px;'>TRANSFORMATION</p>","data11":{"phase":"test","type":"new","category":"fruit","test_type":"unrelated_test","word":"TRANSFORMATION"},
"test8":"<p style='font-size: 48px;'>FINISH</p>","data12":{"phase":"test","type":"new","category":"fruit","test_type":"unrelated_test","word":"FINISH"},
},
{"stimulus1":"<p style='font-size: 48px;'>AIDS</p>","data1":{"phase":"study","type":"old","category":"disease","word":"AIDS"},
"stimulus2":"<p style='font-size: 48px;'>CANCER</p>","data2":{"phase":"study","type":"old","category":"disease","word":"CANCER"},
"stimulus3":"<p style='font-size: 48px;'>FLU</p>","data3":{"phase":"study","type":"old","category":"disease","word":"FLU"},
"stimulus4":"<p style='font-size: 48px;'>FRIENDSHIP</p>","data4":{"phase":"study","type":"distinct","category":"disease","word":"FRIENDSHIP"},

"test1":"<p style='font-size: 48px;'>AIDS</p>","data5":{"phase":"test","type":"old","category":"disease","test_type":"cat_test","word":"AIDS"},
"test2":"<p style='font-size: 48px;'>CANCER</p>","data6":{"phase":"test","type":"old","category":"disease","test_type":"cat_test","word":"CANCER"},
"test3":"<p style='font-size: 48px;'>FLU</p>","data7":{"phase":"test","type":"old","category":"disease","test_type":"cat_test","word":"FLU"},
"test4":"<p style='font-size: 48px;'>FRIENDSHIP</p>","data8":{"phase":"test","type":"old","category":"disease","test_type":"distinct_test","word":"FRIENDSHIP"},
"test5":"<p style='font-size: 48px;'>FORTUNATELY</p>","data9":{"phase":"test","type":"new","category":"disease","test_type":"unrelated_test","word":"FORTUNATELY"},
"test6":"<p style='font-size: 48px;'>OWE</p>","data10":{"phase":"test","type":"new","category":"disease","test_type":"unrelated_test","word":"OWE"},
"test7":"<p style='font-size: 48px;'>SMELL</p>","data11":{"phase":"test","type":"new","category":"disease","test_type":"unrelated_test","word":"SMELL"},
"test8":"<p style='font-size: 48px;'>INFANT</p>","data12":{"phase":"test","type":"new","category":"disease","test_type":"unrelated_test","word":"INFANT"},
},
{"stimulus1":"<p style='font-size: 48px;'>COTTON</p>","data1":{"phase":"study","type":"old","category":"fabric","word":"COTTON"},
"stimulus2":"<p style='font-size: 48px;'>SILK</p>","data2":{"phase":"study","type":"old","category":"fabric","word":"SILK"},
"stimulus3":"<p style='font-size: 48px;'>POLYESTER</p>","data3":{"phase":"study","type":"old","category":"fabric","word":"POLYESTER"},
"stimulus4":"<p style='font-size: 48px;'>FIFTH</p>","data4":{"phase":"study","type":"distinct","category":"fabric","word":"FIFTH"},

"test1":"<p style='font-size: 48px;'>COTTON</p>","data5":{"phase":"test","type":"old","category":"fabric","test_type":"cat_test","word":"COTTON"},
"test2":"<p style='font-size: 48px;'>SILK</p>","data6":{"phase":"test","type":"old","category":"fabric","test_type":"cat_test","word":"SILK"},
"test3":"<p style='font-size: 48px;'>POLYESTER</p>","data7":{"phase":"test","type":"old","category":"fabric","test_type":"cat_test","word":"POLYESTER"},
"test4":"<p style='font-size: 48px;'>FIFTH</p>","data8":{"phase":"test","type":"old","category":"fabric","test_type":"distinct_test","word":"FIFTH"},
"test5":"<p style='font-size: 48px;'>CONSEQUENCE</p>","data9":{"phase":"test","type":"new","category":"fabric","test_type":"unrelated_test","word":"CONSEQUENCE"},
"test6":"<p style='font-size: 48px;'>LOSE</p>","data10":{"phase":"test","type":"new","category":"fabric","test_type":"unrelated_test","word":"LOSE"},
"test7":"<p style='font-size: 48px;'>REAL</p>","data11":{"phase":"test","type":"new","category":"fabric","test_type":"unrelated_test","word":"REAL"},
"test8":"<p style='font-size: 48px;'>ANIMAL</p>","data12":{"phase":"test","type":"new","category":"fabric","test_type":"unrelated_test","word":"ANIMAL"},
},
{"stimulus1":"<p style='font-size: 48px;'>DOG</p>","data1":{"phase":"study","type":"old","category":"animal","word":"DOG"},
"stimulus2":"<p style='font-size: 48px;'>CAT</p>","data2":{"phase":"study","type":"old","category":"animal","word":"CAT"},
"stimulus3":"<p style='font-size: 48px;'>HORSE</p>","data3":{"phase":"study","type":"old","category":"animal","word":"HORSE"},
"stimulus4":"<p style='font-size: 48px;'>RARELY</p>","data4":{"phase":"study","type":"distinct","category":"animal","word":"RARELY"},

"test1":"<p style='font-size: 48px;'>DOG</p>","data5":{"phase":"test","type":"old","category":"animal","test_type":"cat_test","word":"DOG"},
"test2":"<p style='font-size: 48px;'>CAT</p>","data6":{"phase":"test","type":"old","category":"animal","test_type":"cat_test","word":"CAT"},
"test3":"<p style='font-size: 48px;'>HORSE</p>","data7":{"phase":"test","type":"old","category":"animal","test_type":"cat_test","word":"HORSE"},
"test4":"<p style='font-size: 48px;'>RARELY</p>","data8":{"phase":"test","type":"old","category":"animal","test_type":"distinct_test","word":"RARELY"},
"test5":"<p style='font-size: 48px;'>LIP</p>","data9":{"phase":"test","type":"new","category":"animal","test_type":"unrelated_test","word":"LIP"},
"test6":"<p style='font-size: 48px;'>COOL</p>","data10":{"phase":"test","type":"new","category":"animal","test_type":"unrelated_test","word":"COOL"},
"test7":"<p style='font-size: 48px;'>SCRAMBLE</p>","data11":{"phase":"test","type":"new","category":"animal","test_type":"unrelated_test","word":"SCRAMBLE"},
"test8":"<p style='font-size: 48px;'>CURRENTLY</p>","data12":{"phase":"test","type":"new","category":"animal ","test_type":"unrelated_test","word":"CURRENTLY"},
},
]
